### ISSUE TITLE
nested routes scroll to child page top

### ISSUE THREAD

**Issue by MG1992** [reach/router#102]
When I used nested routing, I found that when the subrouting page was too long and the page came in, it was positioned at the head of the self-routing rather than at the top of the entire page.
```
  <Router>
      <Home path="/">
        <About path="about" />
        <Support path="support" />
        <Dash path="dashboard">
          <DashHome path="/" />
          <Invoices path="invoices" />
          <Team path="team" />
        </Dash>
      </Home>
    </Router>
```
cat DashHome.js
```
export default props => (
  <div style={{ height: 1400 }}>
    <h3>Dashboard Home</h3>
  </div>
)
```

above code base on https://reach.tech/router/example/nested-routes

**Comment by baurine** [comment]
hey @MG1992 , why did you close this issue? did you find the solution?

**Comment by grantballmer** [comment]
I've been having this same issue. was there any solution?
