### ISSUE TITLE
How to determine if a path is a valid SPA route?

### ISSUE THREAD

**Issue by hardfist** [reach/router#106]
I have 2 SPA(for example A and B) in my website and they share a Nav Component, which has some links to A and B。
```
const ComponetA;
//nav.js
export default () => {
  return (
    <div>
      <Link to="/page_a/route1" >page A</Link>
      <Link to="/page_b/route2" >page B</Link>
    </div>
  );
};
//A.js
export default () => {
  return (
    <div className="pageA">
    <Nav />
    <Router>
    <ComponentA path="/page_a/router1" />
    </Router>
    </div>
  )
}
//B.js
export default () => {
  return (
    <div className="pageB">
    <Nav />
    <Router>
    <ComponentB path="/page_b/router2" />
    </Router>
    </div>
  )
}

```
I want to determine if the Link to props is a valid route,like "/page_a/route1" is valid in PageA but not valid in PageB, so When I click "page_a/route1" link in PageB,because the path is not a valid It will render nothing.

**Comment by mtliendo** [comment]
You can define a 404 page by[ passing in a `default` prop in your router](https://reach.tech/router/api/RouteComponent).  That way any `Link` components that don't point to a valid route will fallback to that route.
