### ISSUE TITLE
Have separate build w/o create-react-context?

### ISSUE THREAD

**Issue by KyleAMathews** [reach/router#111]
It's not necessary for React 16. Trying to get Gatsby's default bundles as small as possible :-)

**Comment by KyleAMathews** [comment]
Also react-lifecycles-compat

**Comment by KyleAMathews** [comment]
Ended up just aliasing them in Gatsby w/ webpack since there's other packages that'll be using them as well 👌 

https://github.com/gatsbyjs/gatsby/pull/7214

**Comment by grantzvolsky** [comment]
@KyleAMathews Would you consider re-opening this issue? While some may appreciate your solution, it is not always trivially applicable, such as when using CRA.
