### ISSUE TITLE
Router should ignore null/undefined children

### ISSUE THREAD

**Issue by joshtynjala** [reach/router#115]
## Think you found a bug?

Please do one of these things:

~~1.  Don't open an issue, open a pull request with a failing test.~~
2.  Boil down your issue on codesandbox.

https://codesandbox.io/s/n56m06zxxj

I'd like to be able to do something like this:

``` js
<Router>
  { someCondition ? <MyRoute path="mypath"/> : null }
  <OtherRoute path="other"/>
</Router>
```

**Comment by rigobauer** [comment]
Yes, I also have that exact problem right now. I want to set routes depending on the user role (and its privileges), so if the user can't access a section, the corresponding routes shouldn't be available.

As @joshtynjala says, once you put the component with the path, it fails with:

**_'TypeError: Cannot read property 'props' of null'_**

Is there any way to implement that behavior?

**Comment by rigobauer** [comment]
Mmm... I guess a workaround could be to use Location component wrapping the <Router> and, before returning the <Router>, check the pathname... if that route is not included in the allowed list, just return null (or whatever you want to render).

I'll give it a try tomorrow to see if it works.

Seems a little

**Comment by joshtynjala** [comment]
Thank you, @ryanflorence!

**Comment by rigobauer** [comment]
Awesome!
