### ISSUE TITLE
Feature request/question: relative `navigate`, add `withRelativeNavigate` HOC (?)

### ISSUE THREAD

**Issue by euvs** [reach/router#116]
How can I perform a relative programmatic navigation? 

I want to perform a relative navigation. However the `navigate` function  provided by the library only performs absolute navigation. 

I could only find two ways how to perform a relative navigation:
- by using `Link`, or
- by using `props.navigate` injected by `Router`

I've got a component deep down the component tree, and I want to relatively navigate on a button click. Passing `props.navigate` through multiple levels is very cumbersome. 

What would be the best way to achieve this? 

Would it be possible to add a HOC (e.g. `withRelativeNavigate`) or something, that can inject `navigate` function as a prop? 

The  `Link` component already implements relative navigation behaviour. Basically I want its behaviour but as a HOC. Is it possible?

**Comment by mtliendo** [comment]
A new addition to the API likely wouldn't be accepted with the [new version on the horizon](https://reacttraining.com/blog/reach-react-router-future/). Using `Link` would likely be the way to go for deeply nested routes.  Currently, if wanting to provide a HOC, wrapping that functionality would be my suggestion. 

Stay tuned for the new API however which would make this much easier 🎉✨
