### ISSUE TITLE
Embedded Routers in NPM Module Don't Match?

### ISSUE THREAD

**Issue by recipher** [reach/router#123]
Hi. I'm having trouble using an embedded router, where the embedded router isn't in the same repo/module as the top level router.

What I'm doing is illustrated here:

https://gist.github.com/recipher/54d33b7e463275663656af763447f1b8

```
import React from 'react';
import { Router } from '@reach/router';
import { Contributions } from 'contributions-ui';
import { Holdings } from 'holdings-ui';
import { Policy } from 'policies-ui';
import { Layout, NotFound } from './components';

const App = props => {
  return (
    <Router>
      <Layout path='/'>
        <Policy path='policies/:policyNumber/*'>
          <Contributions path='contributions/*'/>
          <Holdings path='holdings/*'/>
        </Policy>
        <NotFound default />
      </Layout>
    </Router>
  );
};

export default App;
```

It's a create-react-app. The ```Policy```, ```Contributions``` and ```Holdings``` components are the embedded router components. If these 3 components are in the same codebase as ```app.js```, everything works fine.

This is an example of an embedded router (this is ```Policy``` above):

```
import React from 'react';
import { Router } from '@reach/router';
import { Policy } from './handlers';

const Routes = props => {
  return (
    <Router>
      <Policy path='/'/>
    </Router>
  );
};

export default Routes;
```

But, if I move the embedded router components into different npm modules (in the example above ```contributions-ui```, ```holdings-ui``` and ```policies-ui```, then it "doesn't work".

Doesn't work means that the sub-level components don't get matched. I've played around with it a bit, and if I remove the ```Router``` from the embedded router and then pass through ```props```, it *almost* works:

```
const Routes = props => {
  return (
      <Policy path='/' {...props}/>
  );
};
```

Now, the ```Policy``` component will be rendered. However, any ```Link``` components in the embedded components don't have relative links working (ie. instead of ```/policies/123/contributions```, I just see ```/contributions```).

Again, everything works fine if it's all in the same codebase, but if the embedded router is in an installed npm module, it fails.

I'm using babel in the installable module:

```babel.rc
[ "preset": "react-app" ]
```

Build:

```BABEL_ENV=production $(npm bin)/babel src --out-dir dist```

Anyone seen this before? Anyone gotten embedded routers working correctly in separate npm modules?

**Comment by recipher** [comment]
peerDependencies is your friend.

**Comment by huchenme** [comment]
@recipher how did you resolve this?

**Comment by recipher** [comment]
Make sure you only have one copy of reach router in your build.

**Comment by huchenme** [comment]
@recipher I do only have one copy of it. my package does not bundle reach router into dist
