### ISSUE TITLE
[Question] How to get params in deeply nested component?

### ISSUE THREAD

**Issue by EJIqpEP** [reach/router#128]
Hello, thanks a lot for your hard work. This router works really good. The only question which I didn't find in docs is how to pass params in deep nested component? In react-router we had withRouter HOC for this. Right know I need to pass in by hands. Any suggestions? 
```
<comp1>
  <comp2>
    <comp3> // here I can get query params
```

**Comment by 416serg** [comment]
I would reach for React's [Context API](https://reactjs.org/docs/context.html)

**Comment by EJIqpEP** [comment]
Would be nice to see somewhere in docs an official suggestion.

**Comment by cdock1029** [comment]
I think the official suggestion would be implied where it describes route components as "just React components", so there's nothing you can't do that you could do with any React Component, and I don't think there's going to be any proprietary solution for it.

So... you could do render props from a parent, React.cloneElement with parent params, Context etc..

**Comment by EJIqpEP** [comment]
I've just find in docs the official solution. There is a component Location which returns location on any level.
```
<Location>
  {({ location })=> {
    // ...
  }}
</Location>
```

Here is a [link in docs](https://reach.tech/router/api/Location)
