### ISSUE TITLE
Provide index.d.ts files.

### ISSUE THREAD

**Issue by Lizhooh** [reach/router#129]
Provide `index.d.ts` files.

**Comment by timdorr** [comment]
This isn't something the library should have to worry about. It's not written in Typescript. Types should go in DefinitelyTyped instead.

**Comment by Lizhooh** [comment]
Although not written in Typescript, you can also add the index.d.ts file. This gives a consistent smart hint on vscode.

**Comment by foisonocean** [comment]
Any update?

**Comment by Lucretius** [comment]
Types appear to be available [here](https://www.npmjs.com/package/@types/reach__router). See also https://github.com/reach/router/issues/11#issuecomment-424277408

**Comment by Lizhooh** [comment]
This is my point of view.

Providing index.d.ts has a better development experience on vscode, and many libraries now offer index.d.ts, whether or not it is developed using typescript.

**Comment by leomeloxp** [comment]
Could any of the repo maintainers let me know if a PR for this would be accepted? I have the commit ready to PR [here](https://github.com/leomeloxp/router/commit/9010c6e5f28e0b0f8361e1f4ab9e370453941cf8) but the contrib document says to not open PR's without announcing it on an issue first for discussions.
