### ISSUE TITLE
Parent Component Rollover when Matching

### ISSUE THREAD

**Issue by jacobp100** [reach/router#134]
I want to apply a layout to some pages, and a variant of the layout another page. However, all these pages exist at the top-level.

If I have a `<Layout navBarHidden={true | false}>`. Should it be possible to add this component twice under Router under the same path, and then continue to the next component if no matches were found? For example,

```jsx
<Router>
  <Layout path="/">
    <Page1 path="page1" />
    <Page2 path="page2" />
  </Layout>
  <Layout path="/" navBarHidden>
    <Page3 path="page3" />
  </Layout>
  <Page4 path="/page4" />
  <NotFound default />
</Router>;
```

Or is there a better way to achieve this?

**Comment by mtliendo** [comment]
Another suggestion would be to wrap `<Layout/>` so that it took in props passed to the different pages.  That would lend itself a bit better to the component model and clean up the code  😊

Hope that helps and thanks for using reach router!
