### ISSUE TITLE
@reach/router 404ing on npm

### ISSUE THREAD

**Issue by mbuttler** [reach/router#139]
Hey folks,

I'm trying to install the package, but it's 404ing on npm's registry.

**Comment by timdorr** [comment]
https://registry.npmjs.org/@reach/router/-/router-1.1.1.tgz downloads just fine for me from here.

If there's a problem, it's with npm. This library can't really do anything about that. I'd reach out on npm's support channels about it.

**Comment by adamUpchurch** [comment]
I'm somewhat of a noob - how do you use the tgz instead of npm install?

**Comment by timdorr** [comment]
That was just to show that the contents of the package are available on npm. That's what npm uses to obtain the package from the registry.

**Comment by mzakov** [comment]
I ran `npm login` and created a username and password, and that fixed the problem.
