### ISSUE TITLE
Router basepath and Link absolute paths

### ISSUE THREAD

**Issue by Seavenly** [reach/router#148]
Is the intended behavior for `Link` absolute paths to not respect the `Router` basepath prop? The following example does not have working links:
https://codesandbox.io/s/vv3q3v9yo0
``` js
import React from "react";
import ReactDOM from "react-dom";
import { Router, Link } from "@reach/router";

import "./styles.css";

const App = () => (
  <Router basepath="/apple">
    <Page path="/">
      <HomePage path="/" />
      <OtherPage path="/other" />
    </Page>
  </Router>
);

const Page = ({ children }) => (
  <div>
    <ul>
      <li>
        <Link to="/">Home</Link>
      </li>
      <li>
        <Link to="/other">Other</Link>
      </li>
    </ul>
    <hr />
    {children}
  </div>
);

const HomePage = () => <h1>Home Page</h1>;
const OtherPage = () => <h1>Other Page</h1>;

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

If I change the Links to relative links then they respect the basepath prop. 
``` js
<Link to="">Home</Link>
<Link to="other">Other</Link>
```

**Comment by gablabelle** [comment]
I'm facing the same issue.

If `basepath` is `/fr`, I was hoping that `<Link to={`/${slug}`} />` would go to `http://www.site.com/fr/slug` but it goes `http://www.site.com/slug`.

I guess we'll have to prefix with the `basepath` ... Weird.

**Comment by kevinrambaud** [comment]
Same thing for me, I'm surprised by this behavior.

**Comment by astik** [comment]
Hi all,
I think this issue can be set as a duplicate from #78.
You should take a look on it, there is a workaround there ... not perfect, but it works ... in a way =)
