### ISSUE TITLE
Question: how to handle prompt when page refresh or redirect?

### ISSUE THREAD

**Issue by booxood** [reach/router#150]

**Comment by donaldpipowitch** [comment]
Is there something like https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/Prompt.md for @reach/router?

**Comment by mtliendo** [comment]
If this still needs addressing, mind providing some more detail on your situation and what blockers you've encountered? A simple codesandbox should be enough to  help out.

cheers and thanks for using reach router!

**Comment by wontwon** [comment]
Why was this issue closed without an answer? :/
