### ISSUE TITLE
Redirect crash when used with Webpack HMR

### ISSUE THREAD

**Issue by ghost** [reach/router#153]
Hi. I've come across the issue with using `<Redirect />` alongside with HMR. The point is that, when HMR is set up and router has a redirect as a child, it prevents app from starting with following error:
```
    <Router>
      <Redirect from="/" to="/home" />
      <Home path="home" />
      <Auth path="auth"/>
      <NotFound default />
    </Router>
```

```
browser.js:34 Uncaught Error: <Router>: Children of <Router> must have a `path` or `default` prop, or be a `<Redirect>`. None found on element type `function Redirect(props) {
  return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(Location, null, function (locationContext) {
    return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(RedirectImpl, _extends({}, locationContext, props));
  });
}`
    at invariant (browser.js:34)
    at eval (index.js:617)
    at mapSingleChildIntoContext (react.development.js:921)
    at traverseAllChildrenImpl (react.development.js:791)
    at traverseAllChildrenImpl (react.development.js:807)
    at traverseAllChildren (react.development.js:864)
    at mapIntoWithKeyPrefixInternal (react.development.js:944)
    at Object.mapChildren [as map] (react.development.js:968)
    at ProxyComponent.render (index.js:273)
```

[Here](https://codesandbox.io/s/yqx0l27rqv) is a codesandbox with the complete code.

I've found out a workaround to make it work: all is needed is to replace `from` property with `path`:
```
// instead of this
<Redirect from="/" to="/home" />
// do this
<Redirect path="/" to="/home" />
```
In this case the condition [here](https://github.com/reach/router/blob/054187e17795c5c2df289109456ce42c48f49343/src/index.js#L476) is evaluated to `true`, otherwise `element.type === Redirect` is `false` due to the way how, I think, HMR works in Webpack: `element.type` has a different reference from the `Redirect` inside library.

**Comment by ryanflorence** [comment]
I like that, cause I'm not excited about doing weird stuff just for react hot loader :)

**Comment by pitops** [comment]
@tpolovyi I think this is still an issue if you work in a monorepo setup. Local packages are symlinked in node_modules. So I understand it correctly then if I change a local package which is a dependency to my main project it won't be detected by RHL. Is that correct?
