### ISSUE TITLE
Syncing with redux state

### ISSUE THREAD

**Issue by Kadrian** [reach/router#156]
Hey, I'm curiuos: Previously, using react-router, I've been happily using [connected-react-router](https://github.com/supasate/connected-react-router) 

Is there something similar for reach router yet? I.e. I'm looking for a way to
1) Update the redux state, when someone navigates using a `Link` or back button
2) Dispatch redux actions like `push()`, `goBack()`, `replace()`, or similar, to trigger a navigation, i.e. change the URL + redux state.

**Comment by johnkorzhuk** [comment]
Same issue here. Using redux-saga and we're upgrading to gatsby v2. Going to be quite the refactor w/o something equivalent to connected-react-router

**Comment by hyanmandian** [comment]
I think that you can listen to history and update your store with these changes.

By the code, the following example should work but after tests I discovered that globalHistory is not exported in the current published package :(

```
import { globalHistory } from '@reach/router';

globalHistory.listen(() => {});
```

So I wrote this workaround to solve that for a while

```
import { LocationProvider } from '@reach/router';

LocationProvider.defaultProps.history.listen(history => {
  console.log(LocationProvider.defaultProps.history.location);
});

```

**Comment by salvoravida** [comment]
@Kadrian may have a look here
https://github.com/salvoravida/redux-first-history

:dancer:

**Comment by carloslfu** [comment]
`redux-first-history` is the simpler solution I found. Thanks, @salvoravida.

**Comment by mpro-dev** [comment]
Trying to use reach router with various external redux location sync libraries. 
Reach seems to create it's own history in a way that isn't compatible with various popular libraries that use history to determine the state of an app.
A rather large amount of common use cases initialise a history using 
`https://www.npmjs.com/package/history`
The item created by this approach does not tally with the reach approach, i've no idea as to what is correct or proper, just that it is raised.

**Comment by mtliendo** [comment]
Generally speaking, syncing your routes with redux [isn't advised in routing](https://reacttraining.com/react-router/core/guides/redux-integration/deep-integration).  In react router the stance was more of a suggestion, but reach router omits recommendations all together.

That being said, I'm happy to see that the community in the comments have ways to solve for your use case 😁🎉
