### ISSUE TITLE
What is the reach-router equivalent to onUpdate? I want to call a function every time the a new route is used.

### ISSUE THREAD

**Issue by JacobMJones** [reach/router#157]

**Comment by adjourn** [comment]
Very easy thing to do in React, don't need additional router API for that, simple example:

```js
componentDidUpdate(prevProps) {
  if (prevProps.location.href !== this.props.location.href) {
    // new href, do stuff
  }
}
```

Can be as simple or complex as you need it to be and you have plenty of lifecycle hooks to choose from.

---

#### `JSON.stringify(this.props.location)`:

```json
  {
    "href": "http://localhost/hello-world",
    "ancestorOrigins": {},
    "origin": "http://localhost",
    "protocol": "http:",
    "host": "localhost",
    "hostname": "localhost",
    "port": "",
    "pathname": "/hello-world",
    "search": "",
    "hash": "",
    "state": {"key":"549857354983"},
    "key": "549857354983"
  }
```

**Comment by JacobMJones** [comment]
Thank you very much :)

**Comment by mateuspontes** [comment]
Do you have to put this `componentDidMount` in every page you want to track? I think it would be better to put this only in one place, maybe on `App.js` with Router definition, like Router's `onUpadate` that you set once.

**Comment by adjourn** [comment]
That's right. Then it's only a question of getting `location` which could easily done like this:

```
<Root>                <- use reach <Location> here to feed location to RouterIsHere
  <RouterIsHere />    <- use location prop in componentDidUpdate or in other hooks
</Root>
```

Note that `Location` is higher in hierarchy than `Router` itself and it works perfectly fine.

**Comment by adjourn** [comment]
That's right. Then it's only a question of getting `location` which could easily done like this:

```
<Root>                <- use reach <Location> here to feed location to RouterIsHere
  <RouterIsHere />    <- use location prop in componentDidUpdate or in other hooks
</Root>
```

Note that `Location` is higher in hierarchy than `Router` itself and it works perfectly fine.

---

There could be an alternative but this is how I do it. I need `location` in component that renders `Router` anyway (e.g routed modals), so this works out perfectly fine.
