### ISSUE TITLE
Navigating breaks `autoFocus`

### ISSUE THREAD

**Issue by jquense** [reach/router#158]
https://codesandbox.io/s/ov6pl4z1o6

Focus shouldn't be moved from an autoFocused element in the page i navigated to.

**Comment by ryanflorence** [comment]
hmm ... so ... I've thought about this before and I'm not sure what I want to do about it.

By default, autofocus only works on initial page load. When we start using `pushState` the browser just doesn't care, so we haven't broken anything ourselves, but we could restore this behavior pretty simply I think.

In usespace:

```jsx
import React from "react";
import { Location } from "@reach/router";
import Component from "@reach/component-component";

let AutoFocusOnNavigation = () => (
  <Location>
    {({ location }) => (
      <Component
        didUpdate={({ prevProps }) => {
          if (prevProps.location !== location) {
            let els = document.querySelector("[autofocus=true]");
            if (els) {
              els[els.length - 1].focus();
            }
          }
        }}
      />
    )}
  </Location>
);

export default AutoFocusOnNavigation;
```

Or we could just bake it in to the router. Which maybe we should do. What do you think?

**Comment by ryanflorence** [comment]
Just had a chat w/ @jquense and I was misunderstanding the problem here.

React polyfills autofocus already, so we're screwing that up by moving focus.

**Comment by ryanflorence** [comment]
If you do `<Router primary={false}/>` it doesn't manage focus anymore.

But `autoFocus` still isn't grabbing focus.

Which is unexpected because it does in your codepen here (https://codesandbox.io/s/5yjp3kl94l)

**Comment by michaelwiktorek** [comment]
https://codesandbox.io/s/3yppojk23q

This still seems to be an issue in 1.2.0 and 1.2.1 - the input is not focused on navigation to "dashboard" even though the "autoFocus" property is set.
