### ISSUE TITLE
Optional route parameters

### ISSUE THREAD

**Issue by tomitrescak** [reach/router#164]
Hi, I'm probably blind but I could not find anywhere information about how to use optional route parameters.

something like `/route/:param/:optionalParam?`

**Comment by timdorr** [comment]
These aren't supported: https://github.com/reach/router/blob/e8325ae7a2d7be0a4e1de266ee15929f85fc2d94/website/src/markdown/pages/credits.md#trade-offs-mostly-compared-to-react-router

> No complex route patterns. *There are no optional params*, or anything like them, it's just static paths, params, and trailing wildcard.

**Comment by tomitrescak** [comment]
@timdorr fair enough! The trailing wildcard will cover at least 85% of cases ... and mine as well ;) Thanks for the super fast response.
