### ISSUE TITLE
Prevent Link from scrolling to top before the animated page transition.

### ISSUE THREAD

**Issue by gablabelle** [reach/router#165]
## Have a question?

Hello, 

I have an animated transition between 2 pages, it slides. Great! ;-)

![screen shot 2018-09-28 at 12 51 17 pm](https://user-images.githubusercontent.com/1565793/46222251-b6044080-c31d-11e8-91d4-af90bf67d277.png)

The problem I'm facing is that when I scroll down at the bottom of a page and use the Link to go to the other page, instead of simply sliding, it scrolls top before sliding.

![screen shot 2018-09-28 at 12 51 28 pm](https://user-images.githubusercontent.com/1565793/46222489-8144b900-c31e-11e8-846d-c24f7bc3aa7a.png)

I would like to prevent that behaviour if possible, so it slides without scrolling top before.

Here is the link to the sandbox : https://codesandbox.io/s/7jl6lr8wxx

Many thanks for your time and help.

**Comment by mtliendo** [comment]
I was able to fix the issue by providing a `primary={false}` prop to the router🎉.  

This will [disable focus](https://reach.tech/router/api/Router) so that it transitions smoothly with the animation.
