### ISSUE TITLE
navigate() persists the scroll position of the previous page as opposed to bringing to the top like <Link/>

### ISSUE THREAD

**Issue by 416serg** [reach/router#166]
I have a sign up form with a sign up button at the bottom of that page that navigates a user to a different page upon submittion. The scroll position persists when `navigate()` happens, where as I was hoping it would reset at the top of the page like `<Link/>` does.

https://codesandbox.io/s/o4v0pzwp0z

**Comment by ordazgustavo** [comment]
I think that this is not an issue with the router, it has to do with the way SPAs work, maybe you can use something like `window.scrollTo(x, y)`.

**Comment by simoroshka** [comment]
I experience the same problem with Links. The page jumps to the container associated with the route. This really should not be the default behavior.
Example: https://codesandbox.io/s/y0jmjj2o8j

**Comment by mcfinley** [comment]
Same issue.

It only happens if you are using nested `<Router>`, the page gets scrolled to the `<Router>` element on the page (or it's children like simoroshka supposed)

**Comment by mcfinley** [comment]
For all who are the same stupid as I am - there is a documented prop for router called `primary` that controls this behavior

https://stackoverflow.com/questions/53058110/stop-reach-router-scrolling-down-the-page-after-navigating-to-new-page

The issue may be closed

**Comment by mtliendo** [comment]
We would never consider you or others "stupid" but your research and help in pointing out the `primary` prop is much appreciated 🏅
