### ISSUE TITLE
Question about Push State

### ISSUE THREAD

**Issue by stuartflanagan** [reach/router#174]
## Have a question?

Questions are welcome. They'll usually be answered with a link to some docs.

Also please join our Spectrum community (https://spectrum.chat/reach)!

I am developing a GatsbyJS site and thus am using @reach/router as a result. It is a great router!
I have an issue while trying to implements some page transitions.

I am using `react-pose` for the transitions. I feel it relies on a POP and a PUSH state to initiate the exit and entry animations.

When outputting the location property I only see a POP added and thus there is no animation when linking from 1 page to the next. If I click the link to the same actual page I do see both a POP and a PUSH state occur and the animation triggers.

I am wondering what I need to do to get the 2 location states added so that the animation can trigger on change of page not just linking to the same page?

An example illustrating this is here:
https://newer-volcanics.surge.sh/index.html

If you use the navigation to change pages you will not see the background fade in and out.
If you use the navigation to link to the same page you see the background animation.
I am logging location in the console an you will see a POP and a PUSH when linking to the same page but only a single POP when switching pages.

Any help greatly appreciated.

Kind regards,

Stuart

**Comment by stuartflanagan** [comment]
Should I ask this question somewhere else? Do you think it is more a GatsbyJS issue than a Reach Router one?

**Comment by mtliendo** [comment]
This sounds like more of a question of how to use `react-pose` with reach-router.  Happily however, the team over at react-pose have a sandbox up on [how to do just that](https://popmotion.io/pose/learn/route-transitions-reach-router/) 🎉

Hope this helps!
