### ISSUE TITLE
Can I set state without providing a location?

### ISSUE THREAD

**Issue by atrauzzi** [reach/router#177]
Quick question -- what would my best option be to set state on the current location without causing navigation?

My most immediate need for this is to store the state of whether the main application menu is open and whether to show a back button for the current view.  The main reason why I liked having these in react router V4 was so that various views and concerns could work with them from any level.

**Comment by gustavopch** [comment]
You could to the following:
```js
navigate(samePath, {
  replace: true,
  state: newState
})
```

**Comment by atrauzzi** [comment]
That's currently how I do it, although I'm worried that internally this might be interpreted as visiting the same route again.

**Comment by pederklev** [comment]
You could see if replaceState solves your problem:
https://developer.mozilla.org/en-US/docs/Web/API/History_API#The_replaceState()_method

**Comment by mtliendo** [comment]
Because of the simplicity of reach/router, I would suggest a tradeoff solution of storing your state in a global store.  In which case, passing context or using a library like redux would both work.

Hope that helps! And thanks for using reach router!😁
