### ISSUE TITLE
memorySource state off by one from stack

### ISSUE THREAD

**Issue by atrauzzi** [reach/router#180]
Looking at `history.js`, I can see this for the `navigate` function:

![image](https://user-images.githubusercontent.com/115199/47271492-a2748000-d53f-11e8-9228-b84d4df33bf1.png)

~Looking at the documentation, the *global* `navigate` function [appears to support state](https://reach.tech/router/api/navigate).  Is the difference between these two intentional?~

> Note: Links in text are to a current commit in my open source project.  So you can see the examples and usage there.

What I'm seeing right now is that [when I try to navigate, while also passing state](https://github.com/atrauzzi/gerty/blob/1668a06c74501a0dfe089710389175ae123716ef/src/Layer/GertyMui/Component/GertyAppBar.tsx#L99), [it's always showing as `undefined`](https://github.com/atrauzzi/gerty/blob/1668a06c74501a0dfe089710389175ae123716ef/src/Layer/GertyMui/Component/GertyApp.tsx#L76-L82).

![image](https://user-images.githubusercontent.com/115199/47271738-8ffb4600-d541-11e8-9622-2184a205631f.png)

**Comment by Lucretius** [comment]
Hi there!

I am wondering where you are seeing this alternative definition of `navigate`?  I see [this](https://github.com/reach/router/blob/master/src/lib/history.js#L45) in history.js and it appears to include the state option.

**Comment by atrauzzi** [comment]
Hmm, that's interesting. Okay, let me dig into things some more on my end. That's definitely weird.

**Comment by Lucretius** [comment]
Sure thing, if its any help - I also just tried the state passing bit locally and it looks to be working.  I wonder if perhaps you've imported another library that also does some sort of navigation and accidentally referenced the `navigate` from that package?

**Comment by atrauzzi** [comment]
Ah, so it looks like transpilation is changing the signature.  I suppose that's what I get for trying to look at transpiled code 😉 

Although that still doesn't explain why I'm not getting state set when I call `this.history.navigate(…, { state: { … }});`.

**Comment by atrauzzi** [comment]
As I continue to dive into the code, it looks like things start here with [`get location`](https://github.com/reach/router/blob/master/src/lib/history.js#L16-L18).  This eventually gets to the [`getLocation` anonymous function](https://github.com/reach/router/blob/master/src/lib/history.js#L1-L7).

```javascript
let getLocation = source => {
  return {
    ...source.location,
    state: source.history.state,
    key: (source.history.state && source.history.state.key) || "initial"
  };
};
```

I'm at a loss at the moment as to why `state` keeps coming back as undefined.  Would have to keep digging, but any insights from anyone are more than welcome!

**Comment by Lucretius** [comment]
Navigate is a primary API method, so I don't think you want to call it as a property on the history object but instead as a normal function call.  Notice how it is imported and used in [the docs](https://reach.tech/router/api/navigate)

**Comment by atrauzzi** [comment]
I guess the problem is that the component I'm trying to call navigate from is not itself under the router.

When I import and call the global `navigate` function, I get an error saying `Failed to execute 'assign' on 'Location': '/wee' is not a valid URL.`.

Not sure why it says that when my passed-along reference to history can navigate to `/wee` just fine...

**Comment by atrauzzi** [comment]
Ah, that's because it's using a totally different globally initialized history object: https://github.com/reach/router/blob/master/src/lib/history.js#L117

I'm in an electron application, so I have to manually initialize one with a memory source.

**Comment by atrauzzi** [comment]
##### Found it!

As I keep digging... I dropped some super-manual tracing in `history.js`, because I feel like something definitely weird is going on.

This is what I call:
```typescript
await this.history.navigate("/wee", { state: { appMenu: !open } });
```

---

And with my crude tracing in place, this is what happens:

```
memorySource.state (0) == {}
memorySource.states == [{}]
memorySource.stack == [{"pathname":"/","search":""}]
memorySource.state (0) == {}
memorySource.states == [{}]
memorySource.stack == [{"pathname":"/","search":""}]
memorySource.state (0) == {}
memorySource.states == [{}]
memorySource.stack == [{"pathname":"/","search":""}]
memorySource.pushState() - start - state == {"appMenu":true,"key":"1540514225529"}
memorySource.pushState() - index++ - 0 -> 1
memorySource.pushState() - stack.push({"pathname":"/wee","search":""})
memorySource.pushState() - states.push({"appMenu":true,"key":"1540514225529"}
memorySource.pushState() - finish - states[1] == {"appMenu":true,"key":"1540514225529"}
memorySource.state (1) == {"appMenu":true,"key":"1540514225529"}
memorySource.states == [{},{"appMenu":true,"key":"1540514225529"}]
memorySource.stack == [{"pathname":"/","search":""},{"pathname":"/wee","search":""}]
memorySource.state (1) == {"appMenu":true,"key":"1540514225529"}
memorySource.states == [{},{"appMenu":true,"key":"1540514225529"}]
memorySource.stack == [{"pathname":"/","search":""},{"pathname":"/wee","search":""}]
memorySource.state (1) == {"appMenu":true,"key":"1540514225529"}
memorySource.states == [{},{"appMenu":true,"key":"1540514225529"}]
memorySource.stack == [{"pathname":"/","search":""},{"pathname":"/wee","search":""}]
memorySource.state (1) == {"appMenu":true,"key":"1540514225529"}
memorySource.states == [{},{"appMenu":true,"key":"1540514225529"}]
memorySource.stack == [{"pathname":"/","search":""},{"pathname":"/wee","search":""}]
memorySource.state (1) == {"appMenu":true,"key":"1540514225529"}
memorySource.states == [{},{"appMenu":true,"key":"1540514225529"}]
memorySource.stack == [{"pathname":"/","search":""},{"pathname":"/wee","search":""}]
memorySource.state (1) == {"appMenu":true,"key":"1540514225529"}
memorySource.states == [{},{"appMenu":true,"key":"1540514225529"}]
memorySource.stack == [{"pathname":"/","search":""},{"pathname":"/wee","search":""}]
```
(calls to the `state` getter and one call to `memorySource.pushState` are happening.

Even though the state survives into `pushState`, it seems like the call to `states.push` isn't resulting in it being found.

---

Here's a copy of `createMemorySource`, with the fix in it, I'll be submitting a PR at least to get the concept introduced.  Will gladly amend until @ryanflorence is happy with it.

```
////////////////////////////////////////////////////////////////////////////////
// Stores history entries in memory for testing or other platforms like Native
var createMemorySource = function createMemorySource() {
  var initialPathname = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : "/";

  var index = 0;
  var stack = [{ pathname: initialPathname, search: "" }];
  var states = [{ key: Date.now() + "" }]; // aha!

  return {
    get location() {
      return stack[index];
    },
    addEventListener: function addEventListener(name, fn) {},
    removeEventListener: function removeEventListener(name, fn) {},

    history: {
      get entries() {
        return stack;
      },
      get index() {
        return index;
      },
      get state() {
console.log(`memorySource.state (${index}) == ${JSON.stringify(states[index])}`);
console.log(`memorySource.states == ${JSON.stringify(states)}`);
console.log(`memorySource.stack == ${JSON.stringify(stack)}`);
        return states[index];
      },
      pushState: function pushState(state, _, uri) {

        var _uri$split = uri.split("?"),
            pathname = _uri$split[0],
            _uri$split$ = _uri$split[1],
            search = _uri$split$ === undefined ? "" : _uri$split$;

console.log(`memorySource.pushState() - start - state == ${JSON.stringify(state)}`);

console.log(`memorySource.pushState() - index++ - ${index} -> ${index + 1}`);
        index++;
console.log(`memorySource.pushState() - stack.push(${JSON.stringify({ pathname: pathname, search: search })})`);
        stack.push({ pathname: pathname, search: search });
console.log(`memorySource.pushState() - states.push(${JSON.stringify(state)}`);
        states.push(state);

console.log(`memorySource.pushState() - finish - states[${index}] == ${JSON.stringify(states[index])}`);
      },
      replaceState: function replaceState(state, _, uri) {
        var _uri$split2 = uri.split("?"),
            pathname = _uri$split2[0],
            _uri$split2$ = _uri$split2[1],
            search = _uri$split2$ === undefined ? "" : _uri$split2$;

        stack[index] = { pathname: pathname, search: search };
        states[index] = state;
      }
    }
  };
};
```

**Comment by atrauzzi** [comment]
?

**Comment by probablyup** [comment]
This should be reopened, it's broken.

**Comment by probablyup** [comment]
I came up with this workaround:

```ts
import { createHistory, createMemorySource, NavigateFn } from '@reach/router'
import React from 'react'

export default function useReachMemorySource() {
  React.useDebugValue('useReachMemorySource')

  // Using a memory router to prevent linking into deeper parts of cancel flow
  const source = React.useMemo(() => createMemorySource('/'), [])
  const history = React.useMemo(() => createHistory(source), [source])

  /**
   * Depth functions as an index offset when backtracking to ensure we return to
   * the desired frame. Since goBack() always pushes a new frame onto the stack
   * we need to keep track of how far we need to backtrack to effectively "go back".
   */
  const [depth, setDepth] = React.useState<number>(1)
  const historyRef = React.useRef<NavigateFn>(history.navigate)

  React.useEffect(() => {
    history.navigate = ((to, options) => {
      if (!to) return // ignore empty string destinations

      // @ts-ignore
      historyRef.current(to, options)

      /**
       * For a successful navigate, the depth offset is reset back to one because we
       * only need to go back one "frame".
       */
      setDepth(1)
    }) as NavigateFn
  }, [history, historyRef.current])

  const goBack = React.useCallback(() => {
    /**
     * navigate(-1) is currently broken in Reach's memory source. To work around
     * this we grab the path of the previous history stack entry and push that
     * onto the stack so that we're always creating new entries vs moving back
     * and forth on the stack.
     */
    historyRef.current(
      // @ts-ignore
      source.history.entries[source.history.index - depth].pathname
    )

    /**
     * Depth offset is incremented by two because we're adding to the stack but for future
     * back button presses want to reference the stack value an additional index behind.
     */
    setDepth(depth + 2)
  }, [depth, history])

  return {
    history,
    goBack,
  }
}
```

Then you use it like this:

```tsx
const { history, goBack } = useReachMemorySource()

  return (
    <LocationProvider history={history}>
```

**Comment by atrauzzi** [comment]
I'm not sure this project is as actively maintained as the latest react router anymore.  There was supposedly a migration path off of this one to it going forward.
