### ISSUE TITLE
Update hash without page jump?

### ISSUE THREAD

**Issue by mattoni** [reach/router#189]
Hi, I've got a particular page where I want to update the hash as the user scrolls (and have the location component update as well, so the navigation updates as well). However, trying to set the hash causes the page to try and jump to the hash, causing all kinds of strange behavior.

Is there a way to update the hash without causing the page to jump, similar to what a call to history.pushState would do?

Thanks!

**Comment by niccai** [comment]
Have you tried having a separate Router for this and setting the primary prop to false?  No idea offhand if it will solve your problem, but it sounds like it could.  I do something similar to not have a list jump.

`<Router primary={false}>`

https://reach.tech/router/api/Router

**Comment by mtliendo** [comment]
Thanks @niccai! As you mentioned, `<Router primary={false}>` was designed to handle this use case, though I'll reopen if  more discussion is needed ☺
