### ISSUE TITLE
Index defined within Component 

### ISSUE THREAD

**Issue by AWare** [reach/router#19]
Hi, 

I really like reach router so far, and we're just trying it out for a new project and have come up with a quick question. 

Should a component with Children be able to define its' own index?

https://codesandbox.io/s/w0z9vqo937

I've implemented your idiom for an index defined as a child in the `withoutindex` route, and what I believe should work on the `withindex` route. 

If the answer is yes, I can come up with a test case; but I'm not sure whether this is desired behaviour. 

Thanks,
Alex

**Comment by ryanflorence** [comment]
You need to wrap that floating `<Index path="/" />` in a `<Router />`. Rendering a component when it's not a child of `<Router/>` is just rendering a component.

```jsx
const ComponentWithIndexAndChildren = ({ children }) => (
  <div>
    <Router>
      <Index path="/" />
    </Router>
    {children}
  </div>
);
```

But the way the example is now, without any sibling routes, it'll just always render.
