### ISSUE TITLE
Feature Request: Map URL Params to props

### ISSUE THREAD

**Issue by nathanforce** [reach/router#2]
## Feature Request

How would you feel about a PR that maps URL params to prop names to avoid the tight coupling of parameter names to prop names and reduce potential collisions. I understand there are many ways around this in userland but it could be a nice first class add.

Happy to PR if desired.

**Comment by ryanflorence** [comment]
Seems like that's not different than just changing the parameter name in the path?

**Comment by nathanforce** [comment]
Sometimes that's not an option, for example if the app has an existing url structure in place that for various reasons can't be tweaked.

I guess in the name of lib size and single responsibility we can just keep this in userland.

Utilities like https://recompose.docsforhumans.com/api/mapprops.html solve the problem nicely enough.

**Comment by ryanflorence** [comment]
Maybe I'm misunderstanding, but the only part of the url that becomes a prop to the component are the dynamic segments.

So if you don't want `props.userId` don't do `<User path="/users/:userId"/>` and do `<User path="/users/:whateverId"/>`

The path is already the mechanism to map the URL params to the component.

**Comment by nathanforce** [comment]
D’oh. Not sure what I was thinking.

**Comment by ryanflorence** [comment]
I rarely know what I'm thinking.
