### ISSUE TITLE
Link: Prevent render of LocationProvider

### ISSUE THREAD

**Issue by fabian-hiller** [reach/router#207]
Hi there,

since 1 or 2 weeks I work with **Reach Router** on an bigger application.
On our main menu I use the **Link Component**, to get to another page.

In the **Profiler of the React Devtools** in Google Chrome, I saw that when the **path changed**, the **LocationProvider** of any Link Component renders successively.
Normally only 1 to 3 rendering processes would be necessary, but now because of the LocationProvider there are more than 20.

Why is that? **Is there a way to prevent that?**
I'm worried that there will be performance problems with slower devices.

<img width="622" alt="react-profiler" src="https://user-images.githubusercontent.com/35291865/48828492-22288100-ed70-11e8-9253-90d3f8355330.png">

Thank you!

Best regards,

Fabian Hiller

**Comment by doejon** [comment]
I am experiencing the same issue. It is reproducible every time for me when using the example [1] whilst navigating from home -> about and then hitting the demo-browser's 'back' button.

[1]: https://reach.tech/router/example/active-links

**Comment by ABruel** [comment]
> I am experiencing the same issue. It is reproducible every time for me when using the example [1](https://reach.tech/router/example/active-links) whilst navigating from home -> about and then hitting the demo-browser's 'back' button.

Same for me. It's also causing problems with my real application. Mainly when I redirect to the same route with a different query, after 3 or 4 redirects, the browser freezes forever.
Don't know if it helps, but running `getEventListeners(window)` returns more and more listeners to popstate each time I redirect, it gets stuck around 40 (each redirect doubles the last one and it begins with 6). Maybe an event listener not being cleaned?
