### ISSUE TITLE
Is this project still alive or it is just another dead born router?

### ISSUE THREAD

**Issue by maullerz** [reach/router#210]
latest commit 27 sept
41 pull request
It seems that this project don't have any active maintainers, where they?

**Comment by nate770** [comment]
Check out Ryan's update in Spectrum from Nov 17
https://spectrum.chat/reach?thread=1dc72cfe-cfca-44f6-a057-57caada35905

**Comment by pitops** [comment]
2 months later still dead....

**Comment by anant-singh** [comment]
@pitops If you read that update in spectrum, he mentioned "early next year" and by March/April he will be asking for development help. So it's still early to say it's dead

**Comment by zhaoyao91** [comment]
Half year passed by, no update, is it really dead?

**Comment by revskill10** [comment]
It's time to fork, anyone volunteer for an active fork ?

**Comment by NickTomlin** [comment]
related: https://github.com/reach/router/issues/273

For those of us ending up here: https://reacttraining.com/blog/reach-react-router-future/

**Comment by zhaoyao91** [comment]
Now I use https://github.com/Paratron/hookrouter, think it's a better alternative to any other router
