### ISSUE TITLE
additional maintainers needed!?

### ISSUE THREAD

**Issue by evdama** [reach/router#212]
I like reach router a lot and hate to see how much PRs and issues are piling up without being addressed properly and in time.

@ryanflorence I reckon you've a ton of things to do and not enough time to spend the time needed on this repo. Why not make a few more people maintainers so they can merge PRs so that reach router improves steadily. The repo currently seems stale and people are getting frustrated their issues and PRs aren't being addressed in time.

**Comment by nate770** [comment]
Check out Ryan's update in Spectrum
https://spectrum.chat/reach?thread=1dc72cfe-cfca-44f6-a057-57caada35905

**Comment by markusgattol** [comment]
From the link above, Ryan wrote:

> Just wanted to stop in and say hello. My workshop tour is almost over and I've earned enough money to be able to dedicate some time early next year to development.
> I'm really excited to work through the issues/pr tabs on Router and Reach UI, and then start building them out further.
> I expect by March/April to start asking for development help, but just want to get a base started first.
> Thanks for being a part of this community!

Excellent, looking forward to this and the fact that reach router isn't going dormant as I thought it might be...

**Comment by evdama** [comment]
@ryanflorence have you had time to check out some of the PRs yet?

**Comment by evdama** [comment]
closing issue, I've gone with https://github.com/frontarm/navi now
