### ISSUE TITLE
<Redirect /> doesn't have trailing slash.

### ISSUE THREAD

**Issue by rockmandash** [reach/router#213]
Please see this minimum example.
If I `click`, I will go to `/hello` instead of `/hello/`.
I know this question is not really important, but I really want my URL to be more `semantic` as possible, because I have `index.html` in my `/hello/` url.

```javascript
import React, { useState } from "react";
import ReactDOM from "react-dom";
import { Redirect } from "@reach/router";

function App() {
  const [on, setOn] = useState(false);
  return (
    <div>
      {on && <Redirect noThrow to="/hello/" />}
      <button
        onClick={() => {
          setOn(!on);
        }}
      >
        click
      </button>
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

**Comment by mtliendo** [comment]
>"All questions are important since they will usually lead to some form of understanding."
>
> -me (just now)

 I see what you're saying, however the router [strips the slashes out](https://github.com/reach/router/blob/master/src/index.js#L521) and then [recomposes them](https://github.com/reach/router/blob/master/src/index.js#L565)  as intended behavior.
