### ISSUE TITLE
IE 11 is not supporting.

### ISSUE THREAD

**Issue by rockmandash** [reach/router#214]
Every time I call navigate(), IE 11 will refresh the whole page to the new URL, and all my application context will be lost, cause it not usable.
React Router will not have this problem, I'm talking about push state, not the hash router.
But I really like reach-router, can somebody have a temporary workaround for me.
Thank you very much.

**Comment by peter-mouland** [comment]
without seeing your code, my initial thoughts is that there is a JS error which is causing the anchors to act like normal, _non-SPA_,  links.  Are you able to build a tiny repo to reproduce the problem?

**Comment by rockmandash** [comment]
@peter-mouland it's really weird, my bigger project will refresh when navigating, but when I want to build a minimum app on IE11, the problem goes away....
I will have to take more time to dig into it......

**Comment by rockmandash** [comment]
@peter-mouland I have a working demo now.
Please see this [website](https://www.pcalifewedo.com.tw/) using IE11.
Scroll down and you will see some photos, after clicking those photos, I call navigate('/post/some-id') it will refresh the entire page.

**Comment by peter-mouland** [comment]
hey, sorry - to be more clear, I meant are you able to share a tiny code-repo which has the problem?

Doing this (stripping out _all_ code) really helps to debug the problem. I often find that it is something i've introduced that caused the bug.

It sounds like by your comment (4th Dec) that the problem isn't in reach/router as when building a small demo, the problem disappeared.

**Comment by rockmandash** [comment]
@peter-mouland Yes, thank you for your kindness.
I can't reproduce the problem, sorry, because I don't know why this happens.
When I build a really tiny repo and use IE11 to browse it, the navigation won't trigger the refresh page.
But when I use it quite some time in a project, the problem will show up, I don't know why this happens.
To be more clear, I only use three APIs that reach router provides

- `<Match />`
- `<Location />`
- `navigate()`

And my website is reach hooks only website, this is all I know so far.

**Comment by sastels** [comment]
@rockmandash @peter-mouland Any further thoughts into this? Just noticing this issue with our code https://github.com/cds-snc/report-a-cybercrime

Thanks!

**Comment by mtliendo** [comment]
The troubleshooting is much appreciated ❤

However, since the router is working in ie11 when in a small app, but sometimes not in a larger one, it sounds like it may be an outlier of a different piece of code 🤔

Gonna close for now, but if the issue keeps persisting and reproducing in a smaller app isn't helping, feel free to see if anyone can spend some time troubleshooting on stackoverflow or the spectrum chat.

~Thanks for using reach router!
