### ISSUE TITLE
npm package includes file not in the repo

### ISSUE THREAD

**Issue by stefanprobst** [reach/router#215]
The npm package includes `es/lib/ManageScroll.js`, which is not in this repo. Where is it coming from?

**Comment by kevinrambaud** [comment]
From ES Modules build, see https://github.com/reach/router/blob/master/build/build.js#L13

**Comment by stefanprobst** [comment]
That compiles the `src` folder, yes. But that does not contain a `ManageScroll.js` (which is not in the commonjs build dir btw).

**Comment by timdorr** [comment]
Looks like something got copied over from the Reach workshops: https://github.com/reach/modern-advanced-react-workshop/blob/master/09-suspense/lecture/src/lib/ManageScroll.js
