### ISSUE TITLE
Destructuring assignment problem on some old browsers

### ISSUE THREAD

**Issue by Draktors** [reach/router#217]
There is a problem on some some old browsers with the destructuring assignment. Babel 6 use `object.assign()` if the browser support this function and a custom function for others. But, browser like ios safari 7, accept `object.assign()` but not support it.

So I guess, to fix it, we would have to update Babel 6 to Babel 7.

Thank you very much.

**Comment by mtliendo** [comment]
Hi @Draktors 👋🏽 
As you mentioned, tweaking your babel configuration to either use a later version, or transpile/polyfill to add support would be the way to do if I understand correctly.

**Comment by jedwards1211** [comment]
@mtliendo I've been thinking about the awkwardness of publishing non-ES5 and how it still hasn't really caught on, and while searching for popular packages that do publish non-ES5 I found `@react/router` as an example.  Many popular packages like `react` and `@apollo/client` still publish pure ES5 (except for maybe `import` and `export` statements -- nothing else).

However, I don't see any warnings in the documentation site about transpiling this package.  Right now the webpack docs still [have examples of excluding `node_modules`](https://webpack.js.org/loaders/babel-loader/#root) and big advice to exclude it if babel is slow.  So transpiling anything inside `node_modules` is still not mainstream and package authors should document if users will need to transpile their package.
