### ISSUE TITLE
Question: Will Reach Router support React Fiber?

### ISSUE THREAD

**Issue by bansalvks** [reach/router#218]
Hi Team,

I am about to start a new project in React Fiber. And as you know React Fiber is going to depreciate some most used life cycles of a component with some more features.

I would love to know if you are going to support it or not.

Many Thanks for building such a amazing project,
Vikas Bansal

**Comment by mtliendo** [comment]
Hi!👋🏽 and thanks for using reach router!

Feel free to take a look at [this blog post](https://reacttraining.com/blog/reach-react-router-future/) on the site to get a sense of what's going on with routing :)
