### ISSUE TITLE
path prop ambiguity

### ISSUE THREAD

**Issue by guywald1** [reach/router#22]
First off, this is a great effort and an awesome project (though I'm a bit biased because I'm down with anything @ryanflorence comes up with). Accessibility is so important. Thank you!

Might be a non-issue, but I was wondering - isn't overriding the `path` prop when rendering the `Router` children problematic? I think, for example, of devs migrating to reach and having to refactor accordingly because it gets shadowed. This has been one of the benefits of render props vs. HOCs, for example;hot worrying about ambiguity. So I understand the appeal, and it's definitely easier this way, but why not just a `<Route />` component?

**Comment by ryanflorence** [comment]
You can make a route component if you want.

```jsx
const Route = ({ path, component:Comp, ...rest} ) => <Comp {...rest} />
<Route path="/whatever" component={Thing}/>
```

Or use @reactions/component (soon to be moved to @reach/component-component)

```jsx
import Component from "@reactions/component"

<Router>
  <Component
    path="/whatever"
    render={(props) => (
      <div>Do your thing with {props.uri}</div>
    )}
  />
</Router>
```
