### ISSUE TITLE
`location.search` for serverside rendering

### ISSUE THREAD

**Issue by chrishelgert** [reach/router#222]
## Feature Request

Hi, great job building this router! :)

A little problem i found while using this router is, that everytime a Page requires a search param - the site has to be rendered on the client again, as the search is always an empty string on the server.

**Location SSR:**
```
{ pathname: '/search?q=jeans', search: '', hash: '' }
```

**Location CSR:**
```
{"href":"http://localhost:3000/search?q=jeans","ancestorOrigins":{},"origin":"http://localhost:3000","protocol":"http:","host":"localhost:3000","hostname":"localhost","port":"3000","pathname":"/search","search":"?q=jeans","hash":"","state":null,"key":"initial"}
```

**Workaround if anyone also needs this:**

```
import { parse, parseUrl } from 'query-string'
const searchArgs = typeof window === 'object'
    ? parse(location.search) // CSR
    : parseUrl(location.pathname).query // SSR

// searchArgs = { q: 'jeans' }
```

**Comment by JiiB** [comment]
@chrishelgert here is why you get an empty string: https://github.com/reach/router/commit/8a562629a9473a80c9ca1563b94cf4012dbc114a

**Comment by luishdz1010** [comment]
The server location could take a `href` parameter and we can internally parse it with `new URL(href)`, then we extract all relevant parts of the url and pass them down to the context. This way there is not information lose whatsoever in the server.

**Comment by ehrencrona** [comment]
This seems to have been resolved in [a commit from end of April 2019](https://github.com/reach/router/commit/b1f97bae9813c20b6e0f509b0819610c9fc034b6) and can therefore presumably be closed?
