### ISSUE TITLE
createMemorySource() should parse search 

### ISSUE THREAD

**Issue by jkjustjoshing** [reach/router#223]
When passing a route string to `createMemorySource()`, it doesn't respect any search params that are added to the path string. This causes unexpected behavior when using `<LocationProvider>`, as shown in this reproduction - https://codesandbox.io/s/mo5o359n39

This might be related to #222

**Comment by 0xR** [comment]
I'm having the same issue. This is the code that causes it:
https://github.com/reach/router/blob/master/src/lib/history.js#L69-L71

**Comment by 0xR** [comment]
I found this workaround:
```js
    const source = createMemorySource('/');
    source.history.replaceState(
      null,
      '',
      `/experiments?${new URLSearchParams({
        key: 'value'
      })}`,
    );
```
