### ISSUE TITLE
Children of <Router> must have a `path` or `default` prop

### ISSUE THREAD

**Issue by dshimkoski** [reach/router#224]
Happy New Year! And thanks for the super slick router!

Unfortunately, it doesn't appear to be working properly with Apollo Client:

> <Router>: Children of <Router> must have a `path` or `default` prop, or be a `<Redirect>`. None found on element type `function ProductList() ...

I created a barebones example with an Apollo Query in a route and posted the repo here: https://github.com/dshimkoski/apollo-reach-error

Created with the following commands:

```bash
npx create-react-app apollo-reach-error
yarn add apollo-boost react-apollo graphql @reach/router
```

If I replace the element that renders the Query with plain text the error doesn't occur.

I can also add `default` to [ProductList](https://github.com/dshimkoski/apollo-reach-error/blob/master/src/App.js#L51) to get things working, although I obviously don't want to do that.

Any idea what's going on here?

Thanks!

**Comment by dshimkoski** [comment]
Sorry, this was an ID 10-T error.

I was composing the routes improperly, i.e., nesting components directly inside `<Router>` children.

**Comment by gagan2005** [comment]
> Sorry, this was an ID 10-T error.
> 
> I was composing the routes improperly, i.e., nesting components directly inside `<Router>` children.

Could you please elaborate on what were you doing wrong.I am facing the same issue and maybe I am doing the same mistake as yours
