### ISSUE TITLE
TypeError: Cannot convert a Symbol value to a string when using React.lazy

### ISSUE THREAD

**Issue by maieonbrix** [reach/router#233]
Hello !

I am using create-react-app.
Here are my dependencies : 

```
"dependencies": {
    "@reach/router": "1.2.1",
    "react": "16.7.0",
    "react-dom": "16.7.0",
    "react-scripts": "2.0.3"
  }
```
I am getting an error when using React.lazy with reach/router.

Here is a link to the buggy code within a codesandbox : https://codesandbox.io/s/2zy8p8w070
or my github : https://github.com/maieonbrix/reach-router-bug-repro

or you can see it here : 

```
import React, { Suspense } from "react";
import ReactDOM from "react-dom";
import { Router } from "@reach/router";

import "./styles.css";

const Home = React.lazy(() => import("./Home"));

function App() {
  return (
    <div className="App">
      <Router>
        <Suspense fallback={<div>loading...</div>}>
          <Home exact path="/" component={Home} />
        </Suspense>
      </Router>
    </div>
  );
}

const rootElement = document.getElementById("root");

ReactDOM.render(<App />, rootElement);
```
I am getting this error : 

<img width="813" alt="screenshot 2019-01-24 at 00 11 25" src="https://user-images.githubusercontent.com/16226376/51643489-edea6000-1f6c-11e9-9404-3b9ba8cc6d45.png">

Thank you for such a great package Ryan !

**Comment by sseppola** [comment]
I suspect you cannot use the `Suspense` component as a direct child of `Router`. 

Instead you can do like this:
```
function createLazyRoute<T extends RouteComponentProps>(
  RouteComponent: React.ComponentType<T>
) {
  return function(props: T) {
    return (
      <React.Suspense fallback={<Loader />}>
        <RouteComponent {...props} />
      </React.Suspense>
    );
  };
}

const AsyncSettingsRoute = createLazyRoute(
  React.lazy(() => import('./modules/viewer/routes/SettingsRoute'))
);
```

Hope that helps.

**Comment by maieonbrix** [comment]
Clever ! It seems indeed to be the issue, I didn't read the highlighted error (in red) only the Cannot convert Symbol thing ... maybe it's worth to add this in the doc ?

Or maybe I should never lazily import a Route component but only the sub-components that its containing..

What do you think @ryanflorence 

Thank you for your time @sseppola :)

**Comment by chiefcll** [comment]
Can this be reopened? Will Reach router ever support Suspense out of the box? I'd like to avoid wrapping my components...
