### ISSUE TITLE
Incorrect behavior of related nested links

### ISSUE THREAD

**Issue by maksimsemenov** [reach/router#234]
Not totally sure if it is a bug or I'm doing something wrong.

The codesandbox example: https://codesandbox.io/s/6z64v83y5n

If I click on the `dashboard` link first and then the navigation works and I'm seeing the `Dashboard` component. However, if I click on the `Relative route` link, while I'm still on the `/dashboard` route, I'm expecting that I will be navigating to `/dashboard/relative`, but instead I'm taken to the `/relative`.

Going through the source I found that `Link` component resolves its `to` property to `href` attribute using `baseuri` value that it gets from context. In my case the `baseuri` value is `/`, while I'm expecting it to be the `/dashboard`.

So, I really not sure if it is the bug or I'm missing something.

If it is the correct behavior, then how can I make nested relative links work, i.e. to add another uri segment to the existing location rather than replacing it from the root?

**Comment by colindcampbell** [comment]
I believe that the nav has to be a child within Dashboard in order for the relative link to work properly

**Comment by mtliendo** [comment]
@colindcampbell is right in how nest works. The docs have a similar example to the one you provided (thanks for giving sandbox btw, it really helps!) that might help: https://reach.tech/router/example/nested-routes
