### ISSUE TITLE
Can we use a Regex to match several paths while declaring a route ?

### ISSUE THREAD

**Issue by micabe** [reach/router#237]
Can we use a Regex to match several paths while declaring a route ?

**Comment by MarcusCemes** [comment]
Hi,
It would be nice to have more control over matched parameters as well, such as in Express.js:

https://expressjs.com/en/guide/routing.html#route-parameters
```
To have more control over the exact string that can be matched by a
route parameter, you can append a regular expression in parentheses (()):

Route path: /user/:userId(\d+)
Request URL: http://localhost:3000/user/42
req.params: {"userId": "42"}
```

It would reduce the need to do custom routing within components after testing parameters.

**Comment by oveddan** [comment]
Was this ever done? I need this feature for my project

**Comment by zkSharks** [comment]
I'm very disappointed that there doesn't seem to be support for regex-based path matching, as the default React Router allows.  I may need to return to the standard React Router because of this.

**Comment by welkinwong** [comment]
I need this feature too

**Comment by jndietz** [comment]
Honestly we shouldn't be using @reach/router anymore - tanstack router and react router v6 are far superior.
