### ISSUE TITLE
Question: UX around leaving unsaved form

### ISSUE THREAD

**Issue by gyzerok** [reach/router#245]
Hello everyone!

**Setup:**
* We are using GatsbyJS which in turn uses Reach Router.
* Our UI supports both desktop and mobile screens.
* On one of the pages I have a wizard-like form with multiple steps.
* Currently we are not saving form state in persistent memory (e.g. local storage), but we are plunning to add it at some point later

**Problem:**

We want to prevent user from accidentally going back from the form by pressing browser back button. Same as for example GMail is doing when you try to leave it before everything was finished.

In your docs I've found out that one of your trade-offs is:
> No history blocking. I found that the only use-case I had was preventing the user from navigating away from a half-filled out form. Not only is it pretty easy to just save the form state to session storage and bring it back when they return, but history blocking doesn’t happen when you navigate away from the app (say to another domain). This kept me from actually using history blocking and always opting to save the form state to session storage.

You have your reasons not to support this functionality and I am not trying to make a "feature request". I am looking here for advices on how to solve it. What would be your recommendations?

I've looked myself through the docs and couldn't find anything except the quote above. Sorry if I missed something.

**Comment by mtliendo** [comment]
No worries, I apologize it's taken a bit to get back and hope you have found a solution in the meantime.  We can definitely work on getting the docs updated with a general purpose example!
