### ISSUE TITLE
Allow absolute urls (url schema != component nesting structure)

### ISSUE THREAD

**Issue by mnieber** [reach/router#246]
Nested components in a `Router` create a nested URL structure, but sometimes I'd like my nested component to use an absolute URL:

    function UrlRouter() {
      return (
        <Router>
          <AppFrame
            path="/app">
            <MainPage
              path="main" 
              comment="relative path"/>
            <SignInPage
              path="/site-root/please/sign-in/"
              comment="absolute path"/>
          </AppFrame>
        </Router>
      );
    }

**Comment by revskill10** [comment]
I guess you don't want to just use `<a>` tag here, for the reason of client-side only reload page. I'd love to here more what's the best way to programmatically navigate with `<a>` tag ?

**Comment by mnieber** [comment]
@revskill10 This is only related to creating the URL structure in the `Router`, it's independent from navigation that structure.

**Comment by Haqverdi** [comment]
good idea

**Comment by mtliendo** [comment]
Just to understand more, is your use case such that knowing the environment has many site roots and can't be hardcoded in?

**Comment by mnieber** [comment]
Hi @mtliendo, no, site-roots are unrelated (in my use-case, I just have one). This is just about using a url that does not reflect the html nesting structure.

**Comment by ryanflorence** [comment]
We supported that in React Router v1-3, but there were composition tradeoffs we quit making in v4 (and also here in @reach/router).

Looks like `AppFrame` wraps all of your routes, so it doesn't need to be a route component at all:

```jsx
function UrlRouter() {
  return (
    <AppFrame>
      <Router>
        <MainPage path="app/main" />
        <SignInPage path="site-root/please/sign-in" />
      </Router>
    </AppFrame>
  )
}
```

If it doesn't wrap all routes, then you can do all sorts of things to get the UI and the URLs that you want:

```jsx
function SignInPage() {
  return (
    <AppFrame>
      <div>stuff</div>
    </AppFrame>
  )
}

function Register() {
  return <div/>
}

function UrlRouter() {
  return (
    <Router>
      <AppFrame path="app">
        <MainPage path="main" />
        {/* these are wrapped w/ the route + layout coupling */}
      </AppFrame>

      {/* other nested paths can also get it automatically*/}
      <AppFrame path="account">
        <Profile path="profile" />
      </AppFrame>

      {/* this can use it in its own render logic (see SignInPage) */}
      <SignInPage path="site-root/please/sign-in" />

      {/* and this doesn't use it at all */}
      <Register path="not/using/app/layout" />
    </Router>
  )
}
```
