### ISSUE TITLE
Children without paths

### ISSUE THREAD

**Issue by devuxer** [reach/router#248]
Warning to anyone who ever tries to do something like this (spoiler: it doesn't work):

```js
function Register({ store }) {
    const homeUrl= getUrl("/home");
    return (
        <Router>
            <NotFound default />
            <RegisterPanel path="/" />
            <AccountLayout path="success" pageName="Registration Received">
                <>
                    <p>Your registration has been received.</p>
                    <p>Please check your email for a confirmation link.</p>
                </>
            </AccountLayout>
            <AccountLayout path="already-exists" pageName="Account Already Exists">
                <>
                    <p>An account has already been created for this email address.</p>
                    <p>
                        Please <Link to={homeUrl}>log in</Link>.
                    </p>
                </>
            </AccountLayout>
        </Router>
    );
}

export default observer(Register);
```

If you test the routes "success" or "already-exists", you will get an error you might find unhelpful:

> Uncaught TypeError: Cannot convert a Symbol value to a string

If you convert those fragments (`<>...</>`) to divs (`<div>...</div>`), you will get a somewhat more useful error:

> Children of <Router> must have a `path` or `default` prop, or be a `<Redirect>`

@ryanflorence,

It might be worth considering an "all or nothing" approach to requiring a `path` attribute on children--i.e., for a given node, allow no child or all children to have a path, but don't allow a mixture of children with and without a path.

At the very least, in the case of a React fragment, it would be better to have the "must have a path" error instead of the "cannot convert a Symbol" one.

**Comment by WilhelmErasmus** [comment]
I'd also like for nodes without path to be rendered regardless if the tree path matches

**Comment by ryanflorence** [comment]
#289 fixed this
