### ISSUE TITLE
Ranks Comments Err

### ISSUE THREAD

**Issue by FengShangWuQi** [reach/router#254]
https://github.com/reach/router/blob/4cd2e31297f2293ba701a6f1146fb55a29a26c26/src/lib/utils.js#L218

https://github.com/reach/router/blob/4cd2e31297f2293ba701a6f1146fb55a29a26c26/src/lib/utils.js#L221

https://github.com/reach/router/blob/4cd2e31297f2293ba701a6f1146fb55a29a26c26/src/lib/utils.js#L222

https://github.com/reach/router/blob/4cd2e31297f2293ba701a6f1146fb55a29a26c26/src/lib/utils.js#L233

https://github.com/reach/router/blob/4cd2e31297f2293ba701a6f1146fb55a29a26c26/src/lib/utils.js#L235

According to code, the rank should be

static > dynamic > root > splat

rather than

https://github.com/reach/router/blob/4cd2e31297f2293ba701a6f1146fb55a29a26c26/src/lib/utils.js#L16

![image](https://user-images.githubusercontent.com/17982705/54819951-833d7280-4cd8-11e9-9e87-10beac089c4f.png)

As the picture shows.

**Comment by ryanflorence** [comment]
The tie breaker is `index`

https://github.com/reach/router/blob/4cd2e31297f2293ba701a6f1146fb55a29a26c26/src/lib/utils.js#L247

Those two paths are a tie.
