### ISSUE TITLE
[Feature Request] Add prop for setting page title

### ISSUE THREAD

**Issue by SeanMcP** [reach/router#256]
## Explanation

A descriptive title for each page is [an important accessibility feature (W3)](https://www.w3.org/WAI/test-evaluate/preliminary/#title). Neither Reach nor React Router handle this natively; it's left to developers to implement, and it is too often ignored. I think Reach, with its focus on accessibility, should address this.

## Proposal

I'm proposing a `title` prop passed to the children of `Router` that will update the page title when that component is mounted. It would look something like this:

```jsx
render(
  <Router>
    <Home path="/" title="Example - Example.com" />
    <Article
      path="article/:articleName"
      title={({ articleName }) => `${articleName} - Example.com`}
    />
  </Router>
)
```

The `title` prop would accept either a string or a function that returns a string. A function `title` will be passed any route params for reference.

If no `title` is provided, the page title would remain unchanged.

## Thoughts?

I know that the intention of this project is to keep the API light, but I think the benefit of adding this feature would outweigh the cost. What do you think?

**Comment by adjourn** [comment]
My opinion is that it's a bit slippery slope because there are so many other tags that should be set and we'd end up reimplementing libraries that already do this. E.g which usually work like this:

```jsx
return (
  <div>
    <XYZHeadLibrary
      title={props.articleName}
      desc={props.articleDesc}
      // and other tags
    />
    <div>Article content</div>
  </div>
);
```

**Comment by SeanMcP** [comment]
> My opinion is that it's a bit slippery slope because there are so many other tags that should be set and we'd end up reimplementing libraries that already do this.

That's a good point that I didn't consider.

However, page title has a particular role in accessibility; I think that would distinguish it from the rest of the `head` tags.

**Comment by mtliendo** [comment]
I agree that it would be a nice addition, however as @SeanMcP mentioned, it can lend itself towards feature-creep if this was handled by the router.

React doesn't disallow dynamically setting the title with native JS, but if wanting to do it in a more component based way, [react-helmet](https://github.com/nfl/react-helmet) has solved for this use case as well.

Gonna close, but the thoughts are much appreciated and thanks for using reach router!
