### ISSUE TITLE
Why does Router render a div in the DOM?

### ISSUE THREAD

**Issue by florian-bd** [reach/router#270]
You can see that in the examples:

```
<div tabindex="-1" role="group" style="outline: none;"><div><h2>Welcome</h2></div></div>
```

Why is that? This makes it harder to layout

**Comment by programarina** [comment]
The accessibility tools are not aware of the changing routes on SPA so it looses focus while transitioning. This library adds one more div wrapper that returns focus to the beginning of the page as it was refreshed. You can find similar solutions here https://github.com/ReactTraining/react-router/issues/5210

**Comment by florian-bd** [comment]
Ok, interesting!
Thank you for answering :)

**Comment by TroyWolf** [comment]
If I understand the accessibility issue correctly, why would we ever need more than one of those extra DIV layers in our app? I am seeing one added for every nesting level in my routes. If I'm on a page that is nested 2 layers into my Router, I have 3 of those injected divs.

![Screenshot from 2020-11-19 13-50-23](https://user-images.githubusercontent.com/6349163/99716897-478b1b00-2a6e-11eb-8f1c-efbe9537fb2f.png)
