### ISSUE TITLE
Can I control the scroll position of an individual component with overflow: scroll?

### ISSUE THREAD

**Issue by rchrdnsh** [reach/router#277]
Hi Ryan and maybe other people that I do not know about XD

I have a GatsbyJS app I'm developing and I'm using a design pattern where the `window.scroll` position is locked to `[0,0]` but I have components that do indeed scroll using the `overflow: scroll` css property. There are a bunch of reasons for this, but the TLDR is that I need to do this and cannot use `position: fixed` or `position: sticky` due to project/browser/usability/bosses-yelling-at-me(not really, but kind-a/sort-a) constraints. Using this design approach I am able to bypass mobile browser decisions that I(we/company) consider to be user hostile, and I am then able to create a more app-like, fluid and enjoyable experience for my users.

This design pattern works great until I navigate to new routes, where I want the scroll position of the `<MainContent>` container to be reset to `[0,0]`, but since this component is not the window element, Gatsby does not seem to know how to do that out of the box.

I have a another app that I have developed using VueJS where I ran into the same problem, but the fix was pretty easy, simply adding a method to the main.js Vue file using the element.scrollTo() DOM API and resetting the scroll position of an individual component using that Vue method, like so:

```js
methods: {
  mainContentScroll () {
    document.getElementById('main-content').scrollTop = 0
  }
}
```

So I would like to know if this is possible using reach router with or without Gatsby, and how I might be able to go about doing it. I already created an issue with the Gatsby team, but they suggested I NOT use this design pattern, which is completely and totally not an option for me. So it's either I figure it out, or switch back to Vue, which I would rather not do at this point, cuz Gatsby is rad, for the most part. Here is a link to that issue with my very long winded explanations and rebuttals, if it is of interest to you and your team:

https://github.com/gatsbyjs/gatsby/issues/14690

Anyhoooo, if there is any way to do this kind of thing in the react world and with reach router and/or gatsby, please let me know. I don't care HOW it's done, I just need some way to do it :-)

Thank you in advance :-)

**Comment by mtliendo** [comment]
Hey @rchrdnsh! Stepping outside of the virtual DOM is typically a red flag, but not explicitly disallowed--especially when dealing with scrolling.  So I'm not sure why `element.scrollTo` wouldn't work in your use case. 

Unfortunately, however, this your solution would be outside of what Reach Router supports, so I'll go ahead and close the issue, but for reference, there are [other forums](https://stackoverflow.com/questions/49253988/automatically-scroll-to-rendered-element-after-setstate-in-react-js) that cover this very topic
