### ISSUE TITLE
Nested router not working in npm package

### ISSUE THREAD

**Issue by huchenme** [reach/router#284]
## [bug]

I have a nested route/nested app with following code

`packages/subpage/src/index.js`

```js
import React from 'react';
import { Router, Link } from '@reach/router';

const Home = () => <h2>Subpage Home</h2>;
const Sub1 = () => <h2>Sub1</h2>;
const Sub2 = () => <h2>Sub2</h2>;

const Subpage = () => {
  return (
    <div>
      <h1>Subpage</h1>
      <nav>
        <Link to="./">Home</Link> - <Link to="sub1">Sub1</Link> -{' '}
        <Link to="sub2">Sub2</Link>
      </nav>
      <Router>
        <Home path="/" />
        <Sub1 path="sub1" />
        <Sub2 path="sub2" />
      </Router>
    </div>
  );
};

export default Subpage;
```

and a main app using the Subpage from a monorepo

`main/src/index.js`

```js
import Subpage from 'subpage'

<Router>
    <Dashboard path="/" />
    <Subpage path="subpage/*" />
</Router>
```

## Problem

if Subpage is created as a file in main app, (./subpage.js), everything is working as expected

if Subpage is imported as a package (monorepo/npm) and `main` file is pointing to the same file, clicking route in subpageB will have a wrong URL (if you click "Sub2", URL should be '/subpage/sub2', but it is '/sub2' instead)

Expected: clicking "Sub2" should have url of '/subpage/sub2',
Actual: clicking "Sub2" have url of '/sub2'

Note: if I copy content of `subpage/dist/index.js` and create another file in main app and paste there, it is working as expected as well

**Comment by huchenme** [comment]
I have discovered that the issue is due to duplicate of @reach/router in node_modules, although in `subpage` package `@reach/router` is not exported in dist, but it is added in `devDependencies` and it is installed in `subpage/node_modules`, when main app is trying to load `subpage` package, the dist file is referencing `packages/subpage/node_modules/@reach/router` instead of `main/node_modules/@reach/router`

This issue will only happen in monorepo, and it will not be an issue in real npm package as `@reach/router` is not added to `dependencies`.

I have figured a solution but kind of ugly: remove `@reach/router` from `devDependencies` and add it to root package.json, so that it ensure all instance is referring to same package.

But I hope this issue could be resolved in `@reach/router` itself.

**Comment by jsphstls** [comment]
@huchenme could there be different versions?

Have you considered wrapping `@reach/router` in your own Router package that would be a dependency of the other packages? That way you only have one interface to `@reach/router` and you can apply configuration and extensions as needed.

**Comment by ryanflorence** [comment]
Probably need @reach/router as a peer dependency of the library on npm instead of a direct dependency, otherwise they will each have their own version
