### ISSUE TITLE
Path score

### ISSUE THREAD

**Issue by erasmuswill** [reach/router#285]
When using Reach Router, the scoring algorithm generally works brilliantly. However, I'd love a way to be able to define my own "score advantage". This could be very useful for controlling what route to render when mixing parameters and wildcards.

I'm currently having an issue with adding a suffix: I'm trying to add `*/signin` to catch any signins and make it easy to send the user back to the originating page with `navigate('../')` but my `*/register/:param` route is getting preference.

**Comment by WilhelmErasmus** [comment]
I tried adding this feature in a fork but it seems that `path=/*/signin` and `path="*/signin"` are not even being considered in the match.

I added a log for `route` in https://github.com/reach/router/blob/e8325ae7a2d7be0a4e1de266ee15929f85fc2d94/src/lib/utils.js#L228 and neither of those were showing up in the `route.path` variable.

**Comment by mtliendo** [comment]
The idea of defining your own[ pathranking](https://reach.tech/router/ranking) algorithm is compelling, however it would likely come at the cost of unintended side effects.  

Adding a new construct isn't currently on the [roadmap](https://reacttraining.com/blog/reach-react-router-future/), but if wanting to champion this enhancement, I would hold off until the two libraries are combined.
