### ISSUE TITLE
Location not updating on query param change

### ISSUE THREAD

**Issue by simonunlikely** [reach/router#288]
Hey guys,

I'm having trouble detecting when a query param has changed as the `Location` render prop does not seem to trigger on such changes.

I need to re-render my component to execute some logic and process the params, how should I proceed? Right now I'm forced to create my own history to listen to which sounds a bit overkill..

Thanks!

**Comment by dgading** [comment]
I used something like this, I don't know if it the best option but seemed to work.
```
componentDidUpdate(prevProps) {
      if (this.props.location.search !== undefined && (this.props.location.search !== prevProps.location.search)) {
        // resolve new parameters
        // Fetch new data
      }
    }
```
