### ISSUE TITLE
Link appears as Anonymous in Devtools

### ISSUE THREAD

**Issue by YouWillBe** [reach/router#291]
![image](https://user-images.githubusercontent.com/16474244/62672716-527f8080-b9ce-11e9-8804-ceebf8b197f2.png)
![image](https://user-images.githubusercontent.com/16474244/62672737-63c88d00-b9ce-11e9-9956-b824292121eb.png)
### Then I hide the Context and Location, emmm...
![image](https://user-images.githubusercontent.com/16474244/62672922-0719a200-b9cf-11e9-9c94-38c1911ed03c.png)
### So, does it need a displayName?

**Comment by mtliendo** [comment]
Thanks for providing some awesome details to make fixing this hopefully a straightforward process.  Looks like there's a PR with a potential fix up. I'll revisit once this PR goes through.
