### ISSUE TITLE
Private Routes with Reach Router

### ISSUE THREAD

**Issue by MarioKrstevski** [reach/router#298]
I was wondering, wasn't the point of Reach Router to be able to write routes like normal components, this has the added benefit of readability.

```
<Router>
   <Dashboard path="dashboard" />
   <CompanyDetails path="cd">
        <Employee path=":id">
    </CompanyDetails>
   ...
</Router>
```
But besides Welcoming page, all my routes should be protected, so I would write something like this 
```
<Router>
   <ProtectedRoute
        path={"dashboard"}
        component={Dashboard}
        allowed={["admin, employee"]}
        mustBeAuthenticated
    />
   <ProtectedRoute
        path={"cd"}
        component={CompanyDetails}
        allowed={["admin, employee, visitor, temporary user"]}
        mustBeAuthenticated
    />
   ...
</Router>
```

And it works fine, but I lose the visibility benefit at first glance. 

So my question is, is there a better way to secure your routes, while still writing your routes with the first approach

Example Pseudo Code I have in mind

```
<Router>
   <Dashboard path="dashboard" privateRoute/>
   <CompanyDetails path="cd" privateRoute>
        <Employee path=":id">
    </CompanyDetails>
   ...
</Router>
```

**Comment by ryanflorence** [comment]
I like your ProtectedRoute :)
