### ISSUE TITLE
Route not rendered when URL entered manually

### ISSUE THREAD

**Issue by mgreenbe** [reach/router#300]
Let's say I'm rendering a list/detail view of users, with the route for the user list being `"/"` and the route for the details of the user with a given `id` being `"/:id"`. When I navigate to `"/"` and click on the link to display the info for the user 2 (say) the URL changes to `"/2"` and the info renders, as expected. However, if I navigate to `"/2"` by typing into the URL bar manually and pressing enter (i.e., not clicking through from the list), the user info isn't rendered. Am I using reach router incorrectly?

The CodeSandbox I made kept throwing me CORS errors, so I'm just pasting in the code below.

```jsx
import React from "react";
import { Router, Link } from "@reach/router";

let users = [
  {
    id: 1,
    name: "Leanne Graham",
    email: "Sincere@april.biz"
  },
  {
    id: 2,
    name: "Ervin Howell",
    email: "Shanna@melissa.tv"
  },
  {
    id: 3,
    name: "Joey Joe Joe",
    email: "JoeyJoeJoe@zamoo.pizza"
  }
];

function App() {
  return (
    <div>
      <nav>
        {users.map((user, i) => (
          <Link key={i} to={`/${user.id}`} state={user}>
            {`${user.id} `}
          </Link>
        ))}
      </nav>
      <Router>
        <User path=":id" />
      </Router>
    </div>
  );
}

function User({ location }) {
  let state = location.state;
  return (
    state && (
      <div className="user">
        <div>
          <span>id: </span>
          <span>{state.id}</span>
        </div>
        <div>
          <span>name: </span>
          <span>{state.name}</span>
        </div>
        <div>
          <span>email: </span>
          <span>{state.email}</span>
        </div>
      </div>
    )
  );
}

export default App;
```

**Comment by ryanflorence** [comment]
Just added a guide, it will be in the next website deployment, but you can read it here now:

https://github.com/reach/router/blob/master/website/src/markdown/pages/server-config.md

**Comment by mgreenbe** [comment]
Thanks for the link, @ryanflorence. I'm using `create-react-app`, as the guide recommends for non-server-rendered apps, and the issue remains. Is there further config I need to do so that the server is, to quote the guide, "delivering the same Javascript code at every URL"? Is this hypothetical configuration doable without ejecting from `create-react-app`? Also, and please excuse my simplistic understanding, isn't running entirely on the client and not needing to make subsequent requests to the web server on route changes one of the main advantages of Single Page Apps? Any guidance is highly appreciated!
