### ISSUE TITLE
Page Translation using reach and GSAP?

### ISSUE THREAD

**Issue by aprather51** [reach/router#303]
Starting with Page transition example using Reach-Router and React-Transition-Group/CSSTransition
https://reach.tech/router/example/animation

But, what if I want to animate with it GSAP? GSAP uses pure JavaScript not CSS. So  `TransitionGroup` and  `CSSTransition` wouldn't be necessary right?  I found another example on GSAP that use React-Router
https://stackblitz.com/edit/gsap-react-route-animation

I am trying to utilize to get it work with Reach-Router, since they both router are almost close resemblance with each other.  So far, I made a progress but unfortunately, animation didn't work! Visit codesandbox and see what I have so far. 
https://codesandbox.io/s/dreamy-diffie-h5rny?fontsize=14

I not understanding here. Did I missing something? Please need help?

**Comment by mtliendo** [comment]
Hi @aprather51 👋🏽

Looking at your sandbox example, I see that it's working with reach router as you mentioned.  Outside of that however, I would recommend posting on a discussion forum like stackOverflow or the [spectrum chat group](https://spectrum.chat/reach?tab=posts).  Doing so helps keep the issues for feature requests/bugs and would likely get your issue resolved a bit faster than here.

Thanks for using reach router!
