### ISSUE TITLE
How to implement route cache

### ISSUE THREAD

**Issue by Benew** [reach/router#308]
Like Keep-Alive in vue or react-router-cache-route https://www.npmjs.com/package/react-router-cache-route

The need is super real ;-)

**Comment by owcc** [comment]
Right! Especially when some page include iframe. Keep the state of iframe is more good than unmount it

**Comment by mtliendo** [comment]
Hey! And thanks for using reach/router!

There are a few ways to achieve that.  I think route caching was first made popular by `react-router-redux` (now called [connected-react-router](https://github.com/supasate/connected-react-router)).

Though it's good to note that this package, as well as react-router, don't suggest binding routes to a data store for [a few reasons](https://reacttraining.com/react-router/web/guides/redux-integration).

Another way, would be to throw the state you'd like to persist on [react context](https://reactjs.org/docs/context.html) and initialize the state through a provider.

This package likely won't implement caching baked-in, but hopefully those links are enough to help get you started on rolling your own per your use case.
