### ISSUE TITLE
Matching route with multiple segments at once

### ISSUE THREAD

**Issue by schovi** [reach/router#31]
Hi,

is there/will be there any way how to match multiple segments at once named as one? Like with Ruby on Rails it would be  `path="/*fullName"` or with React Router it can be achieved with `path="/:fullName(.*)?"`

**Example:**

```jsx
<Router>
  <HomePage path="/" />
  <ShowPage path="/*fullName" />
  <HelpPage path="/help" />
</Router>
```

In this example order of routes would be `HelpPage` -> `ShowPage` -> `HomePage`

1. For `/help` it matches `HelpPage`
2. For `/schovi` it matches `ShowPage`
3. For `/schovi/test/...` it matches `ShowPage`
4. For `/` it matches `HomePage`

Thx!

**Comment by ryanflorence** [comment]
Need to get some anchor links in the docs, but look for "Trailing Wildcard" here:

https://reach.tech/router/api/RouteComponent

**Comment by schovi** [comment]
@ryanflorence Thank you. Didn't get that right on the first time. From the documentation, I thought it is used just when you want another Router inside previous.
