### ISSUE TITLE
How to push and pop state to/from history?

### ISSUE THREAD

**Issue by alexiwonder** [reach/router#312]
I hope it's not too much to ask: Can somebody please write a demo to show the correct way to push and pop from history?
What I'm trying to achieve is pushing the state of the component I've already navigate to. When user goes back and then navigates forward to the component again, I pop the pushed state.

**Comment by Rutulpatel7077** [comment]
@mtliendo 

I have the same question! Would you like to put an example, please?

**Comment by Victoriacsl** [comment]
I have the same question! Would you like to put an example, please?
