### ISSUE TITLE
Depency declaration may pull in MIT-incompatible create-react-context 0.2.3

### ISSUE THREAD

**Issue by uhoh-itsmaciek** [reach/router#313]
Hello! Thanks for your work on @reach/router!

It looks like in version 1.2.1 (based on what's coming from `npm`--I don't see a 1.2.1 tag in git), the semantic version declared for one of your dependencies allows a particular version of that library that has a license not compatible with MIT. Specifically, `create-react-context` dependency is declared in package.json as `^0.2.1`, but that allows version 0.2.3, which has [a license](https://github.com/jamiebuilds/create-react-context/blob/v0.2.3/LICENSE) similar to Douglas Crockford's infamous [Good, not Evil license](https://en.wikipedia.org/wiki/Douglas_Crockford#%22Good,_not_Evil%22), which is not a free and open source license. Any chance you could release a 1.2.2 that allows bumping that dependency to 0.3.0 (which reverts to an MIT license and does not appear to have any breaking changes)?

**Comment by sormy** [comment]
easy fix - upgrade to 0.3.0, but it is not clear why library is unconditionally pulling polyfill library.

**Comment by blainekasten** [comment]
If anyone is interested in updating the dependency here to 0.3.0, please submit a PR and I'd be happy to see that through!

**Comment by uhoh-itsmaciek** [comment]
@blainekasten the patch in #319 does that, no?
