### ISSUE TITLE
Get path changes outside Router 

### ISSUE THREAD

**Issue by damianon** [reach/router#318]
Not sure if this is possible yet or if it's a feature request:

`
     const isStart = window.location.pathname === '/';

     {isStart ? <StartHeader /> : <Header toggleTheme={toggleTheme} />}
                    <Router>
                        <StartPage path="/" />
                        <SearchPage path="/search" />
                        <DetailsPage path="/details/:id" />
                        <ProfilePage path="/profile/:id" />

                        <AboutPage path="/about" />
                        <ContactPage path="/contact" />
                        <HelpPage path="/help" />
                    </Router>
`

The stuff outside the router is not rerendered on navigation, therefore the StartHeader stays even when navigating to another page.
Is there a way to change the header, or just a better way to structure this?

**Comment by jacekk** [comment]
@damianon Your `isStart` is declared and defined outside `<Router>` so there is nothing that could listen on changes in the `location.pathname` and then trigger a rerender of your parent component.

One probable  way of doing this is to use the `Match` component --> https://reach.tech/router/api/Match . I think it can work outside your `Router`, so the following snippet shoud give you a hint how to handle this case:

```jsx
const App = () => (
  <Match path="/">
    {(props) => props.match
        ? <StartHeader />
        : <Header toggleTheme={toggleTheme} />
    }
  </Match>
  {/* anything between the header and router ... or nothing as in the above example */}
  <Router>
    <StartPage path="/" />
    <SearchPage path="/search" />
    {/* other routes */}
  </Router>
)
```
Not tested though, but the idea fo solution stays the same - you need to **listen** on location changes.

**Comment by damianon** [comment]
Thanks. That works perfectly.
