### ISSUE TITLE
Question: are hash routes possible?

### ISSUE THREAD

**Issue by jpnelson** [reach/router#32]
Hi! I recently did a conversion from react-router to reach/router , which was surprisingly straightforward!

One question I had was around hash routes – is there an equivalent approach for a hash based route?

In react router I'd use https://reacttraining.com/react-router/web/api/HashRouter , if there's a recommendation, it'd be good to have that listed. If that's not supported, it might be worth calling that out (and if it's intentional, maybe the rationale?) I was able to convert my project to not need HashRouter, but it would've saved some effort in terms of trying different things.

Thanks for a great solution!

**Comment by ryanflorence** [comment]
#25
