### ISSUE TITLE
[QUESTION]How to use reach router with React Context API?

### ISSUE THREAD

**Issue by chloesun** [reach/router#328]
## Question:
How to use reach router with React Context API?

I use `reach router` like this below before and it works fine
```
.....
<Router>
   <ComponentA path="/:id">
   <ComponentB path="/">
<Router>
....
```
I decided to refactor my code with `context` , and the code is refactored to something like this:
```
<GlobalContextProvider>
  <GlobalContext.Consumer>
  {( context) =>{
  return(
  .....
   <Router>
      <ComponentA path="/:id">
      <ComponentB path="/">
   <Router>
   ....
  }

```
After the refactor, the `ComponentA` is not working properly, as the url param prop `id` is not passed 

In the ComponentA.js , test like this:
```
 componentDidMount() {
    const { id } = this.props;
    console.log(id);    // return undefined
  }
```
Also when I `console.log(this.props)` , it returns the same result as `this.context`
Can someone help me understand why this is happening? How to refactor with context properly?

Thanks a lot

**Comment by chloesun** [comment]
Also when I `console.log(this.props) `, it returns the same result as `this.context`

**Comment by chloesun** [comment]
@ryanflorence Could you please take a look at my issue, I've stuck with this one for a while. Thank you very much!

**Comment by mtliendo** [comment]
Hey @chloesun sorry for the delay. 

I get what you're trying to do, though I'm not seeing how you're wanting to use `context` to pass in the `id`. 

Is there a repo or codesandbox I could look at? I'd be happy to get you on the right track 😄

**Comment by chloesun** [comment]
@mtliendo  thanks for your reply! I wrapped the entire app under the `GlobalContext.consumer`, but I still want to pass the url params `id` as a prop just like this example https://reach.tech/router/example/url-params. 
Now for Component A, I can't access `id` from `this.props`, and when I try to `console.log(this.props)`, it logs the same result as `this.context`. Sorry, I don't have a public repo for now.

**Comment by mtliendo** [comment]
A bit tough to know exactly what you're looking for, but I hope this helps 😃 In this example, the `id` can still be access on props, while a lower component can still access context set on the provider:

https://codesandbox.io/s/reach-router-starter-with-context-6t5tq?fontsize=14&hidenavigation=1&theme=dark

**Comment by mtliendo** [comment]
Hope that helps out, I'll go ahead and close, though feel free to post if there's something else going on.

**Comment by chloesun** [comment]
Thanks @mtliendo , my Component that uses url params as prop is deeply nested in the app, I will try to refactor my code.

**Comment by chloesun** [comment]
I finally figure out this issue:

`ComponentA ` is wrapped with HOC, and by adding `{...this.props}` to ComposedComponent, 
![bug](https://user-images.githubusercontent.com/13730281/72559737-7d220f00-3873-11ea-9405-ffeb219a2a06.PNG)

`ComponentA `can access the url params from` this.props`

Please refer this issuehttps://stackoverflow.com/questions/45873414/passing-react-context-through-an-hoc-to-a-wrapped-component

**Comment by 5t33** [comment]
@mtliendo  Unfortunately this does not work using hooks: 

I updated your example here:
https://codesandbox.io/s/reach-router-starter-with-context-hooks-np7w2

Any idea how one might fix this?

**Comment by 5t33** [comment]
Unless I'm doing something wrong?
