### ISSUE TITLE
[feature request] export LocationContext

### ISSUE THREAD

**Issue by vaclavnovotny** [reach/router#345]
Simply by exporting `LocationContext` we unlock users to create hooks or add/modify data passed in Context. 

Don't know what to add more. It is super simple and brings extra power to all users.

**Comment by pret-a-porter** [comment]
@vaclavnovotny pull request https://github.com/reach/router/pull/336 exist already. It is still waiting for review as many others(

**Comment by blainekasten** [comment]
We are exporting some hooks #346 

I'm going to close this as I believe the use case is covered here. Feel free to keep the discussion going. Open to hearing why exporting exposes more options
