### ISSUE TITLE
Multiple parameters in path not properly handled

### ISSUE THREAD

**Issue by DiPSoMaNiE** [reach/router#35]
Hi,

When trying to match multiple parameters in a route path : 

`<Router><Invoice path=":invoiceId-:invoiceName" /></Router>`

The regex `let paramRe = /^:(.+)/;` used in `src/lib/utils` returns a single match in the form of `invoiceId-:invoiceName` with (for example) value `1-somename`.

It would be great to improve this with a regex like `:\w+(\:\w+)?` to match every parameter independently and pass `{invoiceId: '1', invoiceName: 'somename'}` props to the `Invoice` component.

Regards

**Comment by ryanflorence** [comment]
Thanks for the suggestion, I don't intend to provide complex path matching like that. A segment is either static or dynamic, if you want to parse it more than that, you can:

```jsx
<Invoice path=":invoiceSlug"/>

const Invoice = ({ invoiceSlug }) => {
  let [ invoiceId, invoiceName ] = invoiceSlug.split('-')
}
```

**Comment by mnpenner** [comment]
That doesn't help if we want something like `:year-:month` and `:year-:month-:day` to be 2 separate routes 😢
