### ISSUE TITLE
Migrate to Docusaurus or GitBook

### ISSUE THREAD

**Issue by nainardev** [reach/router#357]
I highly suggest you to migrate the documentation to [GitBook](https://gitbook.io) or [docusaurus](https://docusaurus.io/)

**Comment by nainardev** [comment]
Also, currently documentation isn't mobile friendly

**Comment by blainekasten** [comment]
The documentation _works_ right now. I'm happy to accept changes to make it more mobile friendly. But I'm not going to invest time right now changing documentation sources. Thanks though!
