### ISSUE TITLE
Ability to enable history blocking

### ISSUE THREAD

**Issue by adamroyle** [reach/router#36]
What's involved to get history blocking working?

**Comment by ryanflorence** [comment]
https://reach.tech/router/credits

**Comment by adamroyle** [comment]
I understand this is not something you need but I'm wondering if there is some underlying technical reason this can't be implemented, or if it could be implemented in userland code?

**Comment by ryanflorence** [comment]
yeah you could create your own history source and pass it to `LocationProvider`.

https://reach.tech/router/api/LocationProvider

I wasn't really involved with history blocking in react router (and history) but as I understood things, we couldn't reliably block when navigating away from the app (say to google.com) with onbeforeunload. If you dig around the history issues you'll find conversations about it I think, but I'm not sure.

**Comment by granmoe** [comment]
Would there be any concerns with using the window popstate event and doing things imperatively in there? In the listener, you would check the current route, and if you are at the "blocked" route, then either go to a "confirm" route imperatively with `navigate`, *or* set something in redux or apollo that causes a modal to be shown and call `navigate` with the previous route. In either case, you would pass `{ replace: true }` to make it as if the attempted route was never visited.

Is this safe? Advisable?
