### ISSUE TITLE
useNavigation Api routing issue.

### ISSUE THREAD

**Issue by rachit2501** [reach/router#375]
According to the docs:
```
import { useNavigate } from "@reach/router"

const AnalyticTracker = (props) => {
  const navigate = useNavigate();

  return (
    <form onSubmit={() => navigate('../', { replace: true })}>
      {...}
    </form>
  )
)
```

This code should redirect back by one according to my history object. But instead using this is actually taking me to the root location.

**Comment by Harvtronix** [comment]
If you want to go back by one in your history object, you should use `navigate(-1)`.

**Comment by rachit2501** [comment]
But "../" should also achieve the same thing right?. Shouldn't this considered to be a bug?

**Comment by Harvtronix** [comment]
No, if you think of you path as the directories of a filesystem, "." represents the current directory and ".." represents the parent of that directory. So by saying `navigate(../)` you are actually saying: push a new entry onto the history and make it the parent of whatever directory I'm currently in. So for example if your browser is currently navigated to "/a/b/c", that will put a new entry onto the history and move you to "/a/b". If you then called `navigate(../)` again, you'd end up at "/a".

**Comment by rachit2501** [comment]
Oh ok Thanku You.
