### ISSUE TITLE
Reach router gives 404 on subdirectory

### ISSUE THREAD

**Issue by bishtsaurav** [reach/router#387]
Hi,
I am beginner in react and using reach/router. Can anyone solve this when I am opening base url which is http://webshringar.com/demo/ so it is working fine on while navigating from navigation it also works fine but I will refresh any page like about,contact it will show 404.

http://webshringar.com/demo/about ----> will give 404 when refresh or open in window.

**Comment by bishtsaurav** [comment]
after so many research I found the result, for subfolder you have to create .htaccess file and do this…
ImportantPlease add your subfolder path if it is inside your public_html folder for example :- public_html/demo
*****so make changes below RewriteRule ^ /demo/index.html [L] *******

RewriteEngine On
RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} -f [OR]
RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} -d
RewriteRule ^ - [L]

# Fallback all other routes to index.html
RewriteRule ^ /path/to/subfolder/index.html [L]

**Comment by RomanovYurii** [comment]
I was so damn confused by styling of the message above, omfg.
Here's what it was meant to be:
```RewriteEngine On
RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} -f [OR]
RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} -d
RewriteRule ^ - [L]

#Fallback all other routes to index.html
RewriteRule ^ /subfolder_with_reach_router/index.html [L]
```

.htaccess should be put exactly to the website folder. E.g.:
- www
  - another-website.com
  - example.io
    - .htaccess
    - subfolder_with_reach_router

I hope this message will help someone to save a bit of time. <3
