### ISSUE TITLE
Redirect errors in some case using in function component...

### ISSUE THREAD

**Issue by X-neuron** [reach/router#389]
## Think you found a bug?

https://codesandbox.io/s/ecstatic-burnell-u1c69

when access '/' url, SecurityLayout will redirect to '/user/login' 。but error occur!

```
The above error occurred in the <RedirectImpl> component:
Warning: LocationProvider: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.
```

**Comment by ChrisBrownie55** [comment]
You simply forgot to place the `noThrow` property on your `<Redirect />` as was shown in the example you copied this from. This is what it should look like:

```jsx
return <Redirect to={`/user/login?${queryString}`} noThrow />;
```

**Comment by X-neuron** [comment]
yet ,work well ,thanks a lot !
