### ISSUE TITLE
Advice for managing focus with modal

### ISSUE THREAD

**Issue by pdhoopr** [reach/router#39]
Hi there,

I'm in the early stages of a project I'm working that was started with React Router. I saw this library and really like what you're doing with it, so I'm trying to use it instead. 

The only question I have so far is regarding usage with react-modal. In my project, there are some pages that are rendered as modals over top of the current page instead of navigating to a completely standalone page. However, these modals have their own paths, so they're rendered as route components.

Since there was no focus management with React Router, modals would just show up and leave the content behind as is. However, with the focus management built in to Reach Router, the app first focuses on wherever the focusable `div` for the route was rendered, and then react-modal does its thing and focuses the modal content. Depending on the situation, this can cause some jumping/scrolling around the page behind the modal.

I guess I'm just looking for some thoughts about what the behavior should be in this case. I'm totally on board with the built-in focus management; it's one of the draws of using the library for me. I'm just not sure if, in the case of these page modals, I should be doing something else. Maybe there's a way to work around the router focus in special situations like this, since react-modal handles focus, too?

Any suggestions you have are really appreciated!

**Comment by ryanflorence** [comment]
Hmm ... we should probably have a prop to disable focus on specific components for these scenarios. What do you think?

**Comment by pdhoopr** [comment]
Sure, something like the `shouldFocusAfterRender` prop of react-modal? That makes sense to me and would do the trick in this case.

**Comment by ryanflorence** [comment]
We might able to detect if the app managed focus and not do it.

Before a transition we could save off the document.activeElement, then when we'd normally perform the focus, we check if that is still the active element, if it is, then we move focus to the route component, but if it's not, that means the app managed focus (the modal) and we should just leave it alone.

**Comment by pdhoopr** [comment]
Interesting idea. Yeah, I'd be happy to see what I can come up with.

I took a very quick look and just tried logging out `document.activeElement` in a couple of places to see if I could figure out where to implement your suggestions. The first log was in the history listener added in `LocationProvider.componentDidMount`, and the other was in `FocusHandlerImpl.focus`. When I click the link to the modal, the history listener logs out that link as active (so far, so good I think). However when focus fires, that link is still active, whereas I would've hoped the modal had done it's thing at that point.

Anything I'm doing jump out at you as the wrong approach? Entirely possible I'm looking in the wrong places.

**Comment by pdhoopr** [comment]
Although if I do something similar to what you did in 936fd393d04d48d11d9b97ac1563ce2914a636ce and wrap the contents of the `FocusHandlerImpl.focus` function in `Promise.resolve().then()`, `document.activeElement` updates as expected...

**Comment by ryanflorence** [comment]
```js
javascript:(function(){if(window._activeElInterval){clearInterval(window._activeElInterval);delete window._activeElInterval;}else{var activeEl;window._activeElInterval=setInterval(function(){var currentActiveEl=document.activeElement;if(currentActiveEl!==activeEl){activeEl=currentActiveEl;console.log(activeEl);}},200);}})();
```

Drag that text into your bookmarks bar and call it "Log Active Element".

Click it when you want to start logging the active element, it's fantastic. No need to edit any code.

**Comment by ryanflorence** [comment]
gonna track this in the PR.
