### ISSUE TITLE
Hello World Gatsby Fails

### ISSUE THREAD

**Issue by Tony221268** [reach/router#406]
I am new to reach router however I have been trying to get it to work for several days without success.

Believe me, I have hesitated to post this fearing the wrath of the mighty coder against the stupid beginner.  if I have made a mistake fine, please don't attack me but to me this seems to be a fault, if only of poor documentation.

Therefore this morning I did the following:

- Installed a fresh gatsby hello world using gatsby-cli 
- ran gatsby new router https://github.com/gatsbyjs/gatsby-starter-hello-world
- ran gatsby develop, success
- Changed index.html to

```
import React from "react"
import { Router, Link } from "@reach/router"
const App = () => (
  <div>
    <h1>Tutorial!</h1>
    <nav>
      <Link to="/">Home</Link>{" "}
      <Link to="dashboard">Dashboard</Link>
    </nav>
    
    <Router>
      <Home path="/" />
      <Dashboard path="/dashboard" />
    </Router>
  </div>
);

const Home = () => (
  <div>
    <h2>Welcome</h2>
  </div>
);

const Dashboard = () => (
  <div>
    <h2>Dashboard</h2>
  </div>
);

export default App
```

****Note I can't use render(<App />, document.getElementById("root")); since root is not found on Gatsby. Perhaps that is it. 

Run Gatsby Develop, success.

The page renders. 

Click the dashboard link, the page **renders for 1 second then disappears.**  I expected it to behave as per the tutorial.

Given that this is a fresh Hello World site with minimal code direct from the tutorial, either this is a straight bug or a documentation bug (admittendly probably with Gatsby documentation, it being known as terrible)? It could be my local environment. Either way I would really like someone to unblock this for me since I am on the point of abandoning Reach Router.

**Comment by Tony221268** [comment]
OK so after several days I fixed it myself. In short, you need to add this entry to your gatsby-node.js file. In long, do their authentication tutorial and you learn that. Typical Gatsby, appalling documentation but fine once you get it working.

`// Implement the Gatsby API “onCreatePage”. This is
// called after every page is created.
exports.onCreatePage = async ({ page, actions }) => {
  const { createPage } = actions
  // page.matchPath is a special key that's used for matching pages
  // only on the client.
  if (page.path.match(/^\/features/)) {
    page.matchPath = "features/*"
    // Update the page.
    createPage(page)
  }
}`

**Comment by curiousercreative** [comment]
@Tony221268 glad you found a solution. Please close the issue if it doesn't require any attention from the reach router team.

**Comment by Tony221268** [comment]
Not really a solutiion since the issue is documentation but I guess that is not necessarily with reach router.
