### ISSUE TITLE
Router default basepath gets lost after one call to server renderer

### ISSUE THREAD

**Issue by IMalyugin** [reach/router#41]
Calling ReactDOMServer.renderToString second time without having basepath attribute on Router, throws an error - `replace of undefined`.

https://codesandbox.io/s/ykq5z2k7p9

As a result, I have an express server providing SSR, but I only get first response out, all subsequent requests result in an error.

The source of the error is 'basepath' getting lost when passed down to stripSlashes.
Everything is fixed by providing basepath="/" to Router.

**Comment by taurose** [comment]
see https://github.com/reach/router/issues/27

**Comment by IMalyugin** [comment]
Truly, didn't think about digging into closed issues.
