### ISSUE TITLE
[Question] Why cant I pass state when I use navigate(-1)

### ISSUE THREAD

**Issue by sas604** [reach/router#451]
Hello,
Why when I use navigate and pass it -1, the state is not being applied. 

This works 
```JavaScript
<button onClick={ ()=> navigate('/', {state:{id:12345})}>back</button>   
                   
```
But this does not 
```JavaScript
<button onClick={ ()=> navigate(-1, {state:{id:12345})}>back</button>   
                   
```
What am I doing wrong? 
Than you.

**Comment by realamirhe** [comment]
which navigate are you using?

if you are using `history.navigate`, it is implemented this way

https://github.com/reach/router/blob/e203fe612236851a0bd3c77dba693e539a351c62/src/lib/history.js#L75-L78

**Comment by sas604** [comment]
> which navigate are you using?
> 
> if you are using `history.navigate`, it is implemented this way
> 
> https://github.com/reach/router/blob/e203fe612236851a0bd3c77dba693e539a351c62/src/lib/history.js#L75-L78

So, the state is not being passed if there a number in the place of to?  Is there another way to navigate to the previous page and pass the state?

**Comment by realamirhe** [comment]
you can add a wrapper around it.
maybe using something like this
```js
const source = createMemorySource('/') // default route
// will be used in reach-router provider
const history = createHistory(source)
const { navigate } = history
const dangerouslyGoToLastRoute = async state => {
  try {
    source.history.go(-1)
    const lastRoute = source.history.entries[source.history.index].pathname
    source.history.entries.pop()
    if (lastRoute) await navigate(lastRoute, { replace: true, state })
  } catch (error) {
    console.log(error)
  }
}

```
