### ISSUE TITLE
Redirect is not working correctly, are there any points I missed?

### ISSUE THREAD

**Issue by LeoChowChina** [reach/router#46]
I tried to Redirect from root to a path, but it failed with: 
Error
[object Object]
https://codesandbox.io/s/qllp20v3j4

Did I use the Redirect incorrectly?

**Comment by AlanChauchet** [comment]
You are using it correctly, it is just the regular behavior of the Redirect component to throw when redirecting (as explained in the documentation here https://reach.tech/router/api/Redirect).
So to get rid of the exception in development mode, you can add the `noThrow` prop to the Redirect

**Comment by LeoChowChina** [comment]
@AlanChauchet thanks for you comment. I had read the api document several times and tried to use the `noThrow` prop as you said. the URL changed, but the `to` component is not render on page before refresh.

**Comment by AlanChauchet** [comment]
@LeoChowChina looks like we are having the same issue https://github.com/reach/router/issues/47

**Comment by LeoChowChina** [comment]
@shenAwesome @AlanChauchet  I think it's a bug. It should be fixed by @ryanflorence soon...

**Comment by ryanflorence** [comment]
Oh right, `Redirect` mounts before `LocationProvider`, gonna throw a hack in to fix this, might not be the best way to do it, but it'll work.

**Comment by zheeeng** [comment]
@ryanflorence Can we reopen this issue? I have the same problem.

**Comment by darron1217** [comment]
Still problem here
