### ISSUE TITLE
component prop is not applied on Router

### ISSUE THREAD

**Issue by jgoux** [reach/router#48]
Hello,

when we pass a value to the Router's `component` prop, the node stays a `div`.

Repro : https://codesandbox.io/s/8n7xn1k7y9

**Comment by timdorr** [comment]
You also have to set `primary` to `false`:
```js
<Router component="main" primary={false}>
```

**Comment by jgoux** [comment]
Thanks for your answer!

Is there a reason why the primary router can't be anything other than a `div`?

**Comment by timdorr** [comment]
Doesn't look like it. Seems like the easiest thing is to [pass along the `component` prop here](https://github.com/reach/router/blob/master/src/index.js#L194). I'll see about a PR for that.

**Comment by ryanflorence** [comment]
Just need to delete this line, I remember moving around the focus handling and missed that. If it's deleted it'll end up in `domProps` that will make it all the way down to the element.

I can do it, or you can send a PR.

https://github.com/reach/router/blob/2675f56127c921474b275ff91fbdad8ec33cbd74/src/index.js#L159

**Comment by ryanflorence** [comment]
fixed in v1.0.8.

@timdorr I put some notes on the commit about that:

> Note that this is only the first Router in the tree, if you have nested routes, the child routers are still going to be “div”.
>
> I think this is good because usually people are going to use `<main>`, and you shouldn’t have nested `<main>`s

**Comment by timdorr** [comment]
@ryanflorence 04c8ca5 just busted things, since `component` is no longer defined.

**Comment by ryanflorence** [comment]
oh lol ... why was my linter not working?

**Comment by timdorr** [comment]
See my comment above. You're referencing `component`, but haven't actually defined it.

**Comment by ryanflorence** [comment]
Yeah yeah, shipping a fix rn

**Comment by ryanflorence** [comment]
@timdorr looks good now?

**Comment by timdorr** [comment]
![](https://media.giphy.com/media/tkndGHrse5sWc/giphy.gif)
