### ISSUE TITLE
Shouldn't the Provider be above the Consumer? Why should your order be reversed?

### ISSUE THREAD

**Issue by RubyLouvre** [reach/router#49]
example: 

https://reach.tech/router/example/basic

![image](https://user-images.githubusercontent.com/190846/41098913-7c85effc-6a8f-11e8-93b6-4b039b690711.png)

This is the official introduction of Provider（ https://reactjs.org/docs/context.html#provider ）

>Accepts a value prop to be passed to Consumers that are **descendants** of this Provider. One Provider can be connected to many Consumers

Moreover, there are too many internal components between Router and Home. Could you reduce these components?

**Comment by timdorr** [comment]
This is so the relevant elements can inherit context if they are nested. This is common within apps that are broken into "sub-apps" that are unaware of the context they are placed in. This makes your entire component tree more composeable.

**Comment by ryanflorence** [comment]
createContext also allows for default contexts, so you don't actually need a provider :O
