### ISSUE TITLE
Path rankings with nested routes

### ISSUE THREAD

**Issue by pdhoopr** [reach/router#51]
Hey, sorry I've got another question stemming from modals with routes. Say I have a setup like this:

```js
<List path="/users">
  <Delete path="/delete" />
</List>
<View path="/users/:userId" />
```

Imagine this as, say, a table of users with a "Delete" link in each row. When I click "Delete", a modal (at `/users/delete` opens over top of the table. However, user details are shown on their own page and so the table doesn't need to be rendered in the background, which is why I haven't nested the `<View />` route.

The problem I'm seeing is that the `<View />` component is displayed on the `/users/delete` route since the paths getting ranked seem to be `/users/*` and `/users/:userId`. I can think of some ways to work around this (such as also importing `<List />` inside `<Delete />` and rendering it out alongside the modal, then flattening the routes to include a `<Delete path="/users/delete" />`), but I wanted to check if there was a more obvious way to accomplish it that I'm not thinking of.

Thank you!

**Comment by ryanflorence** [comment]
We don't go "deep" to match routes, so each level is ranked independent of its children (otherwise things have to get nutty in the code).

In this case, you'd have to flatten. Should add some docs around this, it's the big gotcha w/ the ranking.

**Comment by shavyg2** [comment]
could you not traverse the children and gather the path parameters,
as long as the path are not wrapped in some other element, eg suspense or another component then you should be able to get the full path, and then use that in the ranking?

Is there a reason for not doing that approach?
compared to just not having nested ranks?

**Comment by WilhelmErasmus** [comment]
I had the same issue - I just refactored my routes to use an absolute name instead of with parameters

**Comment by shavyg2** [comment]
Yikes 😬
