### ISSUE TITLE
Breaks Apollo renderToStringWithData

### ISSUE THREAD

**Issue by mhaagens** [reach/router#70]
I'll try to open a PR with a failing test after work, but just wanted to see if there's already a solution being worked on for this.

When using @reach/router renderToStringWithData from react-apollo returns empty state on the server (doesn't run the queries). Works when I switched back to React Router.

Really excited about Reach Router!

**Comment by ryanflorence** [comment]
Can you make a demo repo? Will reopen if you can provide a test case. Thanks!

**Comment by alaister** [comment]
Was there a solution found for this?

**Comment by joshmanders** [comment]
I've run into this too.
