### ISSUE TITLE
Animation bug (?) with navigate, redirectTo and Redirect

### ISSUE THREAD

**Issue by codepunkt** [reach/router#71]
I've implemented the `FadeTransitionRouter` from the examples in the documentation and can animate between pages using `react-transition-group` just fine. When i use the `Link` component.

When i use the `navigate` or `redirectTo` methods or the `Redirect` component, things break:

![reach-router-navigate-animation](https://user-images.githubusercontent.com/603683/41297976-a88246d0-6e60-11e8-879d-ac5723fc117f.gif)

So far, i don't have a clue why.

**Comment by ryanflorence** [comment]
https://codesandbox.io/s/18282617n3

Works with navigate here.

Happy to reopen if you can provide a codesandbox that exhibits the broken behavior.

**Comment by codepunkt** [comment]
Will try to reproduce tomorrow.

**Comment by codepunkt** [comment]
@ryanflorence Everything seems fine. My problem was that i only have 2 route components, `PrivateRoute` and `PublicRoute`. Both of them do a conditional redirect - one if the user is authenticated, the other if the user is not.

The only two places i used `navigate` where when switching from a private to a public route (logout) and when switching from a public to a private route (login). In both cases, the previous route was re-rendered and did an conditional redirect in addition to the `navigate`, which resulted in the "flickering" you can see in the animated gif.

My solution is converting both private and public route components to `PureComponent`, which prevents the re-render and thus the additional conditional redirect.

Maybe this will help someone in the future :)

**Comment by the-unbearable-lightness-of-being** [comment]
@codepunkt What about with hooks? I am using navigate on the submit from login page to a private component. I am using framer motion for animations. Like you said, everything works fine with Link, but with navigate, the exit prop does not get called. The transition is instantaneous.
