### ISSUE TITLE
pushState of identical URL when clicking a link

### ISSUE THREAD

**Issue by codepunkt** [reach/router#72]
What do you think of doing another pushState when clicking a `Link` to the current url?

E.g. user clicks "/dashboard"-Link while already being on dashboard route. At the moment, this triggers animations (e.g. fading out dashboard page and fading it back in). I don't like this behavior, but i'm not sure if we can generalize this to all other forms of pushState?

**Comment by ryanflorence** [comment]
That's how browsers and routing works by default. We won't be doing anything to try to guess what apps may or may not want to do there. I think you've got two choices:

1. `preventDefault()` on click in the link if you're already there (make sure to check event.button to see if they're trying to right click it, and check modifier keys to see if they're going to open in a new window with control/command)

2. don't do the animation if you're already at the same location.pathname
