### ISSUE TITLE
Router crashes when invalid ref prop is passed in

### ISSUE THREAD

**Issue by Pyrolistical** [reach/router#73]
When `props.ref=undefined` is passed into `Router`, it crashes when trying to get focus.

Repo case in preact: https://codesandbox.io/s/n3mpmk2054
Works fine in react: https://codesandbox.io/s/887o6v4p9j

The createElement spec doesn't allow `ref` to be passed in as a prop, but I found a bug with a combination of preact (https://github.com/developit/preact/issues/1143) + emotion (https://github.com/emotion-js/emotion/issues/718) which does. Reach router should protect itself against bad behaving libs by ignoring `props.ref`

**Comment by ryanflorence** [comment]
Sorry, is there something wrong with the code here or something wrong with the code elsewhere and you just want us to be proactively defensive?

**Comment by timdorr** [comment]
This isn't a Reach Router or React bug. It's very specific to Preact and that combination of libraries: https://github.com/developit/preact/issues/1143#issuecomment-396886244 

Asking Reach Router to protect an unsupported edge case isn't really reasonable, unfortunately. I'd wait for an upstream fix from Preact.

**Comment by Pyrolistical** [comment]
Let me be more clear on how the crash occurs within Reach router and you can consider if this is worth protecting against.

1. `ref` is set to `undefined` on `Router` https://github.com/reach/router/blob/master/src/index.js#L155
2. it gets passed into `RouterImpl` https://github.com/reach/router/blob/master/src/index.js#L181
3. it gets passed into `FocusWrapper` https://github.com/reach/router/blob/master/src/index.js#L225
4. it gets passed into `FocusWrapperImpl` https://github.com/reach/router/blob/master/src/index.js#L253
5. the undefined `ref` overwrites the one on `Comp` https://github.com/reach/router/blob/master/src/index.js#L350
6. `this.node` never gets set
7. this crashes https://github.com/reach/router/blob/master/src/index.js#L323

I would argue the main issue is here: https://github.com/reach/router/blob/master/src/index.js#L350
If we rewrite to
```
        style={{ outline: "none", ...style }}
        tabIndex="-1"
        role={role}
        {...domProps}
        ref={n => (this.node = n)}
```
then domProps which contains the bad ref can never cause `this.node` to be undefined.

Just need to be more careful what you allow to be overwritten

**Comment by timdorr** [comment]
In canonical React, `ref` is never passed in as a visible prop to a component: https://codesandbox.io/s/61p76qj1mz

**Comment by ryanflorence** [comment]
Thanks for verifying that Tim, that was my understanding, too.

I don't want to worry about Preact's idiosyncrasies so I'm closing this issue.
