### ISSUE TITLE
Feature Request - Bound links

### ISSUE THREAD

**Issue by alexkrolick** [reach/router#75]
Proposed API:

```js
import { createRouter } from '@reach/router';

const basepath = '/profile';

const { Router: ProfileRouter, Link: ProfileLink } = createRouter(basepath);

// ...

const ProfilePage = (
  <div>
    <ProfileLink to="/">Home<Link>
    <ProfileLink to="/somewhere">Somewhere</ProfileLink>
  </div>
);
```

The use case for this is to create isolated sub-apps that can be mounted on any root route without prepending the base path to every internal absolute link.

The API is similar to the `createContext` API from React 16.

**Comment by codepunkt** [comment]
What's the difference between your proposal and just nesting links below a single `Router` as described in the "nesting" documentation?

**Comment by ryanflorence** [comment]
Why can’t you just use a relative link?

**Comment by alexkrolick** [comment]
Same reason you don't always use relative imports in JS - sometimes it makes more sense to describe a path top-down. For example a nav-bar component that includes a bunch of component-relative links.

**Comment by ryanflorence** [comment]
```jsx
let ProfileLink = ({ to, ...props }) => (
  <Link to={`/profile${to}`} {...props}/>
)
```

Should do what you want.

I don't want to introduce "relative absolute paths", there's no parallel in the browser for that.
