### ISSUE TITLE
[Question] Enforcing the path of a default route

### ISSUE THREAD

**Issue by jgoux** [reach/router#77]
Hello,

I want to enforce my paths when using a default route. (No "NotFound" page, but a redirect to the "default" location in the tree)

For example I have this structure (I assume it could be a nested router too so it should work relatively) : 
```js
<Router>
  <UserScreen path="user" />
  <MarketScreen default path="market" />
</Router>
```

Here when no route is matched, `MarketScreen` is rendered, but its `path` isn't used. I'd like the "/market" part to be pushed into history and displayed in the address bar too.

I tried using `<Redirect/>` too to achieve this behaviour but couldn't find a working combination.

Is it possible to achieve with the current API?

**Comment by codepunkt** [comment]
what about this

```
<Router>
  <UserScreen path="user" />
  <MarketScreen path="market" />
  <Redirect default noThrow to="/market" />
</Router>
```

**Comment by jgoux** [comment]
Hi @codepunkt ,

Unfortunatly I already tried this.

`Redirect` doesn't seem to work with relative links, so I lose the ability to "isolate" my sub-screens.

In my case I have something like this : 

```js
// Main screen
<Router>
        <Redirect noThrow default to="colisage/*" />
        <ColisageScreen path="colisage/*" />
</Router>

// Inside ColisageScreen, there is a sub-router
<Router>
        <Redirect noThrow default to="enregistrer-tube" />
        <EnregistrerTubeTab path="enregistrer-tube" />
        <ChargerPortoirTab path="charger-portoir" />
        <ChargerMalletteTab path="charger-mallette" />
        <DechargerMalletteTab path="decharger-mallette" />
        <DechargerPortoirTab path="decharger-portoir" />
</Router>
```

So when I type the URL "/whatever" in my app, I'd like it to display : "/colisage/enregistrer-tube" as default.

Does it make sense?

**Comment by ryanflorence** [comment]
You can use this to redirect when they land at the root:

```jsx
<Redirect noThrow from="/" to="enregistrer-tube" />
```

Redirect support `default` is kind of interesting, but are you sure you don't want to tell them the URL they used isn't valid?

**Comment by ryanflorence** [comment]
for now your `<NoMatch/>` and render a `<Redirect to="/wherever"/>`

**Comment by ryanflorence** [comment]
Related? #94

**Comment by jgoux** [comment]
Yes I think this should solve my use case. 😃

**Comment by dnutels** [comment]
Wait, if `Redirect` is going to support relative links, than this:

```
<Redirect to="login" />
```

should be trivial, no? In order to resolve the relative link you need to know the path, somehow. Which means, if the above works, that you have the path. Which, in turn, means you could inject `from` automatically to be the closest predecessor `path`

Am I off here?

**Comment by brion-fuller** [comment]
If this is merge, can we close this issue?

**Comment by SavePointSam** [comment]
I wasn't able to get the `<Redirect />` update to work with a relative path. However, I was able to build a `<NoMatch />` that accomplishes this functionality.

NoMatch (TypeScript)
```tsx
import React from 'react';
import { RouteComponentProps, Redirect } from '@reach/router';

interface Props extends RouteComponentProps {
  to: string;
  isRelative?: boolean;
  noThrow?: boolean;
}

export const NoMatch = ({
  to,
  isRelative = false,
  noThrow = false,
  uri,
}: Props) => {
  if (uri == null) return null;

  const cleanedURI =
    isRelative === true && uri.slice(-1) === '/'
      ? uri.slice(0, uri.length - 1)
      : uri;

  return (
    <Redirect
      noThrow={noThrow}
      from="/"
      to={isRelative === true ? `${cleanedURI}/${to}` : to}
    />
  );
};
```

usage:
```jsx
import React from 'react';
import { Router } from '@reach/router';

import { UsersRoute } from './UsersRoute';
import { NoMatch } from './NoMatch';

const Router = () => (
  <Router>
    <UsersRoute path="users" />

    <NoMatch default isRelative noThrow to="users" />
  </Router>
);
```

**Comment by florianwachs** [comment]
Thanks @SavePointSam !

**Comment by JuananRodriguez** [comment]
Maybe it's a little late, but I attach my humble solution:

`class RelativeRedirect extends React.Component{

    render(){
        let { to, ...rest } = this.props;
        to = to.replace('/', '');
        const pathname = this.props.location.pathname;
        return <Redirect {...rest} to={`${pathname}/${to}`}/>;
    }
}`

And in the Router:

`<Families path={'families'}>
                        <RelativeRedirect from={"/"} to={`list`} default noThrow />
<Families/>
`
