### ISSUE TITLE
Pattern like '/test-location/:userId/article-:articleId.html' is not supported

### ISSUE THREAD

**Issue by kouhin** [reach/router#79]
Hi, I'm trying to use @reach/router in our product but found that partial params is not supported yet. 
Is this will support in the future? 

This is a very common use in real world applications.

react-router 4 works well since it uses path-to-regexp.

```js
expect(matchPath('/test-location/bob/article-123456.html', {
    path: "/test-location/:userId/article-:articleId.html",
})).toEqual({
    path: '/test-location/:userId/article-:articleId.html',
    url: '/test-location/bob/article-123456.html',
    isExact: true,
    params: {
        userId: 'bob',
        articleId: '123456'
    }
});
```

But in @reach/router, this pattern will be failed.

```js
expect(match("/test-location/:userId/article-:articleId.html", "/test-location/bob/article-123456.html")).toEqual({
    params: {
        userId: 'bob',
        articleId: '123456'
    },
    uri: '/test-location/bob/article-123456.html'
  });
```

```
  ● match pattern › encountered a declaration exception

    expect(received).toEqual(expected)

    Expected value to equal:
      {"params": {"articleId": "123456", "userId": "bob"}, "uri": "/test-location/bob/article-123456.html"}
    Received:
      null

    Difference:

      Comparing two different types of values. Expected object but received null.

      59 |
      60 | describe("match pattern", () => {
    > 61 |   expect(match("/test-location/:userId/article-:articleId.html", "/test-location/bob/article-123456.html")).toEqual({
      62 |     params: {
      63 |         userId: 'bob',
      64 |         articleId: '123456'

      at Suite.<anonymous> (src/lib/utils.test.js:61:109)
      at Object.<anonymous> (src/lib/utils.test.js:60:1)
```

BTW, Spring MVC (Java) uses [AntPathMatcher](https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/util/AntPathMatcher.java) to do path ranking and regexp is also supported, it may be used as reference.

**Comment by ryanflorence** [comment]
correct, you'll need to match `/test-location/:userId/:articleSlug`

and then you can do your own parsing on `articleSlug` to get the id out:

```jsx
let [ articleId ] = props.article.slug.match(/article-(.+)\.html$/)
```

**Comment by kouhin** [comment]
@ryanflorence Thank you. 
Seems that it's not so convenient since we also have a lot of patterns such as 😥

- /test-location/:userId/article-:articleId.html
- /test-location/:userId/videolist-:page.html
- /test-location/:userId/imagelist-:page.html
- /test-location/:userId/image-:articleId-:imageId.html
