### ISSUE TITLE
Default route at top level with nested routes

### ISSUE THREAD

**Issue by raja** [reach/router#82]
I am trying to get the NotFound default component to render but App component seems to render for incorrect urls.

Codesandbox is having server issues but here is an example:
```js
import React from "react";
import { render } from "react-dom";
import { Router, Link } from "@reach/router";

const App = ({ children }) => (
  <div>
    <nav>
      <Link to="/">Home</Link> <Link to="dashboard">Dashboard</Link>
    </nav>
    {children}
  </div>
);

const Home = () => (
  <div>
    <h2>Welcome</h2>
  </div>
);

const Dashboard = () => (
  <div>
    <h2>Dashboard</h2>
  </div>
);

const NotFound = () => (
  <div>
    <h2>Not Found</h2>
  </div>
);

render(
  <Router>
    <App path="/">
      <Home path="/" />
      <Dashboard path="dashboard" />
    </App>
    <NotFound default />
  </Router>,
  document.getElementById("root")
);
```

Here is another example of the minimal router from my test app where MainLayout is rendered for ambiguous urls (ie: "/should-not-be-found") without a child component. 

```js
    <Router>
      <MainLayout path="/">
        <Home path="/" />
        <Dashboard path="/dashboard" />
        <Call path="call/:phoneNumber" />
      </MainLayout>
      <PublicLayout path="/auth">
        <Login path="/" />
      </PublicLayout>
      <NotFound default />
    </Router>
```

**Comment by ryanflorence** [comment]
You'll need to move the not-found into the `App` (first example) and then twice in both `MainLayout` and `PublicLayout` because `/` is a match on `MainLayout`.

**Comment by juanialt** [comment]
@ryanflorence what if you want to have the `NotFound` component outside those parents? Your solution don't solve that. In that case you should have the `NotFound` component inside the `MainLayout` or `PublicLayout`. Is there a way to solve that problem?
