### ISSUE TITLE
Uncaught (in promise) RedirectRequest

### ISSUE THREAD

**Issue by zayalexnick** [reach/router#86]
Hello,
I'm using redirectTo in my custom decorator

```
import React from 'react';
import { redirectTo } from '@reach/router';

export default WrapperComponent => class CheckPrivate extends WrapperComponent
{
    componentDidMount()
    {
        if (WrapperComponent.private)
            redirectTo('/auth');

        super.componentDidMount();
    }
}
```

This decorator i apply to my react component
```
import React, { Component } from 'react';
import CheckAuth from '~/utils/checkAuth';

@CheckAuth
export default class extends Component
{
    static private = true;
    static redirect = '/auth';

    render()
    {
        return (
            <h1>Hello</h1>
        );
    }
}
```
I have error: Uncaught (in promise) RedirectRequest { uri: '/auth' }

**Comment by ryanflorence** [comment]
related to #91 

I'll need a codesandbox to investigate further, will reopen if one is provided :)

**Comment by bhanuka-diff** [comment]
Hey any update on this?

**Comment by Rutulpatel7077** [comment]
Same issue +1

**Comment by joserocha3** [comment]
@ryanflorence [here](https://codesandbox.io/s/reach-router-starter-v1-rtfh5) is the issue in a codesandbox. Click on Dashboard to `redirectTo` Home and you will see the error logged in the console.

**Comment by brn** [comment]
@bhanuka-diff @Rutulpatel7077 @joserocha3 
I faced same issue, but I found that reach-router explicitly throw error if Redirect comopnent used,
so if you want to suppress error, pass 'noThrow' props like below.

```
<Redirect noThrow={true} to="/foo/bar/baz"/>
```

**Comment by mtliendo** [comment]
@joserocha3 Thanks for the sandbox.  I'll tackle this later this week unless anyone else calls dibs.

Unrelated to the issue, just a friendly reminder to those reviewing the sandbox to clean up their timeouts to avoid memory leaks 😄 

```jsx
const Dashboard = () => {
  useEffect(() => {
    const id = setTimeout(() => {
      try {
        redirectTo("/");
      } catch (error) {
        console.log(error);
      }
    }, 1000);

    return () => clearInterval(id);
  });
```

**Comment by KelechiOdom10** [comment]
> @bhanuka-diff @Rutulpatel7077 @joserocha3
> I faced same issue, but I found that reach-router explicitly throw error if Redirect comopnent used,
> so if you want to suppress the error, pass 'noThrow' props like below.
> 
> ```js
> <Redirect noThrow={true} to="/foo/bar/baz"/>
> ```

This didn't work when I tried it. Any other suggestions?

**Comment by silnose** [comment]
Hi! same issue with redirectTo(uri). 

Any updates ? :(
