### ISSUE TITLE
potential issue with UMD bundle/Rollup

### ISSUE THREAD

**Issue by tsiq-swyx** [reach/router#93]
I wont be upset if this is closed without comment. but maybe someone here might be able to point me to a solution, or maybe its a rollup config issue.

I am trying to make a static site generator with React, Parcel, and @reach/router. I have tested @reach/router with Parcel and I do know that Parcel can parse it fine. but when I throw babel-register and SSR into the mix that might increase the tech risk a bit.

All i know is that the proximate cause of my error is Parcel interacting with Rollup. When Rollup bundles @reach/router, it generates these lines in `umd/reach-router.js`:

```js
var _react2 = _interopRequireDefault(React);
var _implementation2 = _interopRequireDefault(implementation);
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
exports.default = _react2.default.createContext || _implementation2.default;
```

when I import @reach/router in my Parcel app and run it, `_react2` is simply an object with `{__esModule: true}` and nothing else. so `_react2.default` is undefined and of course `_react2.default.createContext` causes my error:

```
Uncaught TypeError: Cannot read property 'createContext' of undefined
    at Object.parcelRequire.57.react (src.d7884ec9.js:20770)
    at newRequire (src.d7884ec9.js:48)
    at localRequire (src.d7884ec9.js:54)
    at Object.parcelRequire.45.react (src.d7884ec9.js:21351)

(and so on)
```

anyone with UMD/Rollup expertise might be able to point the way?

**Comment by alexkrolick** [comment]
Why is Parcel grabbing the UMD build? It should be finding the ES Module...

**Comment by ryanflorence** [comment]
Yeah, seems weird that parcel is grabbing the UMD build over the ES module build, or even the cjs build. @devongovett @jamiebuilds any ideas?

**Comment by ryanflorence** [comment]
@devongovett thanks for checking it out, yeah that's a typo in the docs. The question is, can you think of any reason parcel is pulling in the UMD file instead of the es or cjs files?

**Comment by alexkrolick** [comment]
@tsiq-swyx you mentioned babel-register, which modifies `require`. Do you think it might be forcing a fall back to package.main/cjs?

**Comment by timdorr** [comment]
[Parcel's resolver favors the `module` entry over `main`](https://github.com/parcel-bundler/parcel/blob/98a293f79bf822bca5f97db9155ee30ddaa03632/src/Resolver.js#L279), and there isn't any other type of package.json entry that would interfere. So, if there's any issue, it's outside of Parcel and in one of its deps.

**Comment by timdorr** [comment]
[`parcelRequire` is only invoked during an HMR](https://github.com/parcel-bundler/parcel/blob/08f938919e4c4008d810170e0b8a4a3fccf27242/src/builtins/hmr-runtime.js#L41), so does this actually occur when bundling for prod usage?

(BTW, @devongovett, I'm digging the readability and quality of the Parcel codebase. Good job! 👍)

**Comment by tsiq-swyx** [comment]
im sorry i havent been responding, i dont know why i didnt get notifications as i am subscribed on this issue. just saw this.

@alexkrolick that could be it, honestly im pretty new to babel-register and its fairly dark/magical right now. i might be trying to rip it out and just go with pure babel-with-parcel instead of doing anything else funky on top of it.

i think its clear at this point that there is nothing inherently wrong with reach router and i just have a bad babel and/or parcel setup. closing this and may reference to it over in the other repos.
