### ISSUE TITLE
Add warning for `navigate` in cDM of app components

### ISSUE THREAD

**Issue by ryanflorence** [reach/router#95]
See #91

**Comment by chooban** [comment]
I was about to come and ask a question about something I think is related. Here's an example app: https://codesandbox.io/s/l728k05onm

If I go to `/` without logging in I expect to be navigated to `/login` and see the form, but instead the URL updates but nothing is rendered. Is this the same issue?

**Comment by Negan1911** [comment]
@chooban I had the same problem and _i think_ that yes, using `<Redirect>` instead of `navigate()` worked properly

**Comment by mtliendo** [comment]
As Ryan mentioned in #91, changing your code to:

```js
const Authorizer = ({ Component, ...props }) => {
  if (!loggedIn) {
    
     return <Redirect to='/login'/>;
  }
  return <Component {...props} />;
};
```

would do the trick 🎩 🐰
